// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AlertService 对外暴露阈值规则增删改查、活跃与历史查询以及确认操作。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Acknowledge 把一条告警标记为已查看,不改变其恢复状态。
 * @param {string} eventID
 * @returns {$CancellablePromise<$models.AlertEventResult>}
 */
export function Acknowledge(eventID) {
    return $Call.ByID(3304186326, eventID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateRule 创建一条有界的 Server 指标阈值规则。
 * @param {model$0.AlertRule} rule
 * @returns {$CancellablePromise<$models.AlertRuleResult>}
 */
export function CreateRule(rule) {
    return $Call.ByID(3972920660, rule).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteEvent 永久删除一条持久化告警事件。
 * @param {string} eventID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function DeleteEvent(eventID) {
    return $Call.ByID(3779832683, eventID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DeleteRule 删除一条规则,并把其活跃告警置为已恢复。
 * @param {string} ruleID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function DeleteRule(ruleID) {
    return $Call.ByID(2480286535, ruleID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListEvents 返回某台 Server 的活跃或历史告警事件。
 * @param {string} serverID
 * @param {string} state
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.AlertEventListResult>}
 */
export function ListEvents(serverID, state, limit, offset) {
    return $Call.ByID(2413769047, serverID, state, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListRules 返回某台 Server 及可选指标下的有界规则列表。
 * @param {string} serverID
 * @param {string} metric
 * @param {boolean} enabledOnly
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.AlertRuleListResult>}
 */
export function ListRules(serverID, metric, enabledOnly, limit, offset) {
    return $Call.ByID(2603948053, serverID, metric, enabledOnly, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * UpdateRule 更新一条阈值规则。
 * @param {model$0.AlertRule} rule
 * @returns {$CancellablePromise<$models.AlertRuleResult>}
 */
export function UpdateRule(rule) {
    return $Call.ByID(3978826401, rule).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AlertEventResult.createFrom;
const $$createType1 = $models.AlertRuleResult.createFrom;
const $$createType2 = $models.ActionResult.createFrom;
const $$createType3 = $models.AlertEventListResult.createFrom;
const $$createType4 = $models.AlertRuleListResult.createFrom;
