// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AlertService exposes threshold rule CRUD, active/history queries, and acknowledgement.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Acknowledge marks one incident reviewed without changing recovery state.
 * @param {string} eventID
 * @returns {$CancellablePromise<$models.AlertEventResult>}
 */
export function Acknowledge(eventID) {
    return $Call.ByID(3304186326, eventID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateRule creates one bounded Server Metric threshold rule.
 * @param {model$0.AlertRule} rule
 * @returns {$CancellablePromise<$models.AlertRuleResult>}
 */
export function CreateRule(rule) {
    return $Call.ByID(3972920660, rule).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteEvent permanently removes one durable alert incident.
 * @param {string} eventID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function DeleteEvent(eventID) {
    return $Call.ByID(3779832683, eventID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DeleteRule removes one rule and recovers any active event.
 * @param {string} ruleID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function DeleteRule(ruleID) {
    return $Call.ByID(2480286535, ruleID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListEvents returns active or historical incidents for one Server.
 * @param {string} serverID
 * @param {string} state
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.AlertEventListResult>}
 */
export function ListEvents(serverID, state, limit, offset) {
    return $Call.ByID(2413769047, serverID, state, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListRules returns bounded rules for one Server and optional Metric.
 * @param {string} serverID
 * @param {string} metric
 * @param {boolean} enabledOnly
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.AlertRuleListResult>}
 */
export function ListRules(serverID, metric, enabledOnly, limit, offset) {
    return $Call.ByID(2603948053, serverID, metric, enabledOnly, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * UpdateRule updates one threshold rule.
 * @param {model$0.AlertRule} rule
 * @returns {$CancellablePromise<$models.AlertRuleResult>}
 */
export function UpdateRule(rule) {
    return $Call.ByID(3978826401, rule).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AlertEventResult.createFrom;
const $$createType1 = $models.AlertRuleResult.createFrom;
const $$createType2 = $models.ActionResult.createFrom;
const $$createType3 = $models.AlertEventListResult.createFrom;
const $$createType4 = $models.AlertRuleListResult.createFrom;
