// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackgroundService exposes controlled background import, resolution, and reset operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get returns the current controlled background resource and bounded Data URL.
 * @returns {$CancellablePromise<$models.BackgroundResourceResult>}
 */
export function Get() {
    return $Call.ByID(1110152750).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Import copies a local image into the controlled data directory and selects it.
 * @param {string} sourcePath
 * @returns {$CancellablePromise<$models.BackgroundResourceResult>}
 */
export function Import(sourcePath) {
    return $Call.ByID(2555775167, sourcePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Reset clears the controlled background and restores the semantic theme background.
 * @returns {$CancellablePromise<$models.BackgroundResourceResult>}
 */
export function Reset() {
    return $Call.ByID(1616453109).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.BackgroundResourceResult.createFrom;
