// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackgroundService 对外暴露受控背景的导入、解析与重置操作。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get 返回当前受控背景资源及有界的 Data URL。
 * @returns {$CancellablePromise<$models.BackgroundResourceResult>}
 */
export function Get() {
    return $Call.ByID(1110152750).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Import 把本地图片复制进受控数据目录并选为当前背景。
 * @param {string} sourcePath
 * @returns {$CancellablePromise<$models.BackgroundResourceResult>}
 */
export function Import(sourcePath) {
    return $Call.ByID(2555775167, sourcePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Reset 清除受控背景并恢复语义主题背景。
 * @returns {$CancellablePromise<$models.BackgroundResourceResult>}
 */
export function Reset() {
    return $Call.ByID(1616453109).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.BackgroundResourceResult.createFrom;
