// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BindingSpikeService 校验 Wails DTO 与上下文契约的基线行为。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Echo 原样返回传入的 DTO,除非 Wails 请求上下文已取消。
 * @param {$models.BindingSpikeRequest} request
 * @returns {$CancellablePromise<$models.BindingSpikeResponse>}
 */
export function Echo(request) {
    return $Call.ByID(709671942, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Wait 阻塞指定时长,Wails 上下文取消时提前返回。
 * @param {number} milliseconds
 * @returns {$CancellablePromise<string>}
 */
export function Wait(milliseconds) {
    return $Call.ByID(2732194950, milliseconds);
}

// Private type creation functions
const $$createType0 = $models.BindingSpikeResponse.createFrom;
