// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BindingSpikeService validates the baseline Wails DTO and context contract.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Echo returns the supplied DTO unless the Wails request context has been cancelled.
 * @param {$models.BindingSpikeRequest} request
 * @returns {$CancellablePromise<$models.BindingSpikeResponse>}
 */
export function Echo(request) {
    return $Call.ByID(709671942, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Wait blocks for the requested duration or returns early when the Wails context is cancelled.
 * @param {number} milliseconds
 * @returns {$CancellablePromise<string>}
 */
export function Wait(milliseconds) {
    return $Call.ByID(2732194950, milliseconds);
}

// Private type creation functions
const $$createType0 = $models.BindingSpikeResponse.createFrom;
