// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConsoleService owns independent Server Console attachments without owning the remote process lifetime.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close is an idempotent alias for Detach and never stops the remote Server.
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Close(sessionID) {
    return $Call.ByID(2918729439, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Detach closes one desktop attachment without stopping the Server process.
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Detach(sessionID) {
    return $Call.ByID(1644925990, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Input sends a command to the attached Java process through its managed tmux session.
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Input(sessionID, data) {
    return $Call.ByID(114764711, sessionID, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Open attaches a desktop view to one running MineOps-managed tmux session.
 * @param {string} serverID
 * @param {number} offset
 * @returns {$CancellablePromise<$models.ConsoleSessionResult>}
 */
export function Open(serverID, offset) {
    return $Call.ByID(289269789, serverID, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.ConsoleSessionResult.createFrom;
