// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConsoleService 独立持有 Server 控制台附着,但不持有远端进程的生命周期。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close 是 Detach 的幂等别名,永不停止远端 Server。
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Close(sessionID) {
    return $Call.ByID(2918729439, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Detach 关闭一次桌面附着,不停止 Server 进程。
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Detach(sessionID) {
    return $Call.ByID(1644925990, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Input 通过受管 tmux 会话向已附着的 Java 进程发送命令。
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Input(sessionID, data) {
    return $Call.ByID(114764711, sessionID, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Open 把桌面视图附着到一个由 MineOps 管理的运行中 tmux 会话。
 * @param {string} serverID
 * @param {number} offset
 * @returns {$CancellablePromise<$models.ConsoleSessionResult>}
 */
export function Open(serverID, offset) {
    return $Call.ByID(289269789, serverID, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.ConsoleSessionResult.createFrom;
