// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopUpdateService 对外暴露桌面发行版检查、准备、取消与重启安装。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel 取消进行中的桌面更新下载。
 * @returns {$CancellablePromise<$models.DesktopUpdateStatusResult>}
 */
export function Cancel() {
    return $Call.ByID(1717835679).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Check 立即解析已配置的 Stable/Beta 通道,不安装任何更新。
 * @returns {$CancellablePromise<$models.DesktopUpdateStatusResult>}
 */
export function Check() {
    return $Call.ByID(2454738339).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Download 下载、校验并准备好可用的桌面更新。
 * @returns {$CancellablePromise<$models.DesktopUpdateStatusResult>}
 */
export function Download() {
    return $Call.ByID(2162867917).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Restart 在可选的未保存内容确认后,重启进入已校验的更新。
 * @param {boolean} discardUnsaved
 * @returns {$CancellablePromise<$models.DesktopUpdateStatusResult>}
 */
export function Restart(discardUnsaved) {
    return $Call.ByID(233459080, discardUnsaved).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Status 返回最近一次桌面发行版检查状态,不发起网络请求。
 * @returns {$CancellablePromise<$models.DesktopUpdateStatusResult>}
 */
export function Status() {
    return $Call.ByID(3332021827).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DesktopUpdateStatusResult.createFrom;
