// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopUpdateService exposes Desktop release checks, preparation, cancellation and restart application.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel cancels the active Desktop update download.
 * @returns {$CancellablePromise<$models.DesktopUpdateStatusResult>}
 */
export function Cancel() {
    return $Call.ByID(1717835679).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Check immediately resolves the configured Stable/Beta channel without installing an update.
 * @returns {$CancellablePromise<$models.DesktopUpdateStatusResult>}
 */
export function Check() {
    return $Call.ByID(2454738339).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Download downloads, verifies and prepares the available Desktop update.
 * @returns {$CancellablePromise<$models.DesktopUpdateStatusResult>}
 */
export function Download() {
    return $Call.ByID(2162867917).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Restart restarts MineOps into the verified update after optional dirty-state confirmation.
 * @param {boolean} discardUnsaved
 * @returns {$CancellablePromise<$models.DesktopUpdateStatusResult>}
 */
export function Restart(discardUnsaved) {
    return $Call.ByID(233459080, discardUnsaved).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Status returns the latest Desktop release-check state without network activity.
 * @returns {$CancellablePromise<$models.DesktopUpdateStatusResult>}
 */
export function Status() {
    return $Call.ByID(3332021827).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DesktopUpdateStatusResult.createFrom;
