// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiagnosticService 向 Wails 暴露隐私受限的诊断归档导出。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Export 把一份脱敏诊断归档写入用户选择的路径。
 * @param {string} destination
 * @returns {$CancellablePromise<$models.DiagnosticExportResult>}
 */
export function Export(destination) {
    return $Call.ByID(2423508251, destination).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DiagnosticExportResult.createFrom;
