// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiagnosticService exposes privacy-bounded diagnostic archive export to Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Export writes one redacted diagnostic archive to the path selected by the user.
 * @param {string} destination
 * @returns {$CancellablePromise<$models.DiagnosticExportResult>}
 */
export function Export(destination) {
    return $Call.ByID(2423508251, destination).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DiagnosticExportResult.createFrom;
