// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadService exposes encrypted proxy credentials, source checks, HTTP reload, and cache management.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckSources runs live connectivity checks through current proxy settings.
 * @returns {$CancellablePromise<$models.DownloadSourceStatusResult>}
 */
export function CheckSources() {
    return $Call.ByID(3563574800).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ClearCache deletes local cached artifacts without changing settings.
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ClearCache() {
    return $Call.ByID(3163762595).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ClearProxyCredential removes the encrypted credential and reloads the HTTP transport.
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ClearProxyCredential() {
    return $Call.ByID(2012580956).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetCacheStatus returns local cache size and configured capacity.
 * @returns {$CancellablePromise<$models.DownloadCacheStatusResult>}
 */
export function GetCacheStatus() {
    return $Call.ByID(2703468650).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetProxyCredentialStatus returns non-secret proxy credential metadata.
 * @returns {$CancellablePromise<$models.ProxyCredentialResult>}
 */
export function GetProxyCredentialStatus() {
    return $Call.ByID(19541765).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SaveProxyCredential writes password bytes only to SQLCipher-encrypted SQLite.
 * @param {$models.ProxyCredentialInput} input
 * @returns {$CancellablePromise<$models.ProxyCredentialResult>}
 */
export function SaveProxyCredential(input) {
    return $Call.ByID(4188724808, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DownloadSourceStatusResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
const $$createType2 = $models.DownloadCacheStatusResult.createFrom;
const $$createType3 = $models.ProxyCredentialResult.createFrom;
