// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadService 对外暴露加密代理凭据、源探测、HTTP 重载与缓存管理。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckSources 按当前代理设置执行实时连通性探测。
 * @returns {$CancellablePromise<$models.DownloadSourceStatusResult>}
 */
export function CheckSources() {
    return $Call.ByID(3563574800).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ClearCache 删除本地缓存构件,不改动任何设置。
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ClearCache() {
    return $Call.ByID(3163762595).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ClearProxyCredential 删除加密凭据并重载 HTTP 传输层。
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ClearProxyCredential() {
    return $Call.ByID(2012580956).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetCacheStatus 返回本地缓存体积与已配置容量。
 * @returns {$CancellablePromise<$models.DownloadCacheStatusResult>}
 */
export function GetCacheStatus() {
    return $Call.ByID(2703468650).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetProxyCredentialStatus 返回非机密的代理凭据元信息。
 * @returns {$CancellablePromise<$models.ProxyCredentialResult>}
 */
export function GetProxyCredentialStatus() {
    return $Call.ByID(19541765).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SaveProxyCredential 仅把口令字节写入 SQLCipher 加密的 SQLite。
 * @param {$models.ProxyCredentialInput} input
 * @returns {$CancellablePromise<$models.ProxyCredentialResult>}
 */
export function SaveProxyCredential(input) {
    return $Call.ByID(4188724808, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DownloadSourceStatusResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
const $$createType2 = $models.DownloadCacheStatusResult.createFrom;
const $$createType3 = $models.ProxyCredentialResult.createFrom;
