// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ErrorService 在桌面日志边界接收前端异常。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ReportClientError 记录一条前端异常,不把堆栈回传给界面。
 * @param {$models.ClientErrorReport} report
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ReportClientError(report) {
    return $Call.ByID(2973556075, report).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
