// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EventSpikeService 发送有界事件批次并负责其关闭生命周期。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Start 按指定间隔开始发送有序批次。
 * @param {number} intervalMilliseconds
 * @param {number} batchSize
 * @returns {$CancellablePromise<void>}
 */
export function Start(intervalMilliseconds, batchSize) {
    return $Call.ByID(1923931640, intervalMilliseconds, batchSize);
}

/**
 * Status 返回事件生成器状态的原子快照。
 * @returns {$CancellablePromise<$models.EventSpikeStatus>}
 */
export function Status() {
    return $Call.ByID(938765502).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Stop 取消活动生成器并返回最终计数。
 * @returns {$CancellablePromise<$models.EventSpikeStatus>}
 */
export function Stop() {
    return $Call.ByID(4074363420).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.EventSpikeStatus.createFrom;
