// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EventSpikeService emits bounded event batches and owns their shutdown lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Start begins emitting ordered batches at the requested interval.
 * @param {number} intervalMilliseconds
 * @param {number} batchSize
 * @returns {$CancellablePromise<void>}
 */
export function Start(intervalMilliseconds, batchSize) {
    return $Call.ByID(1923931640, intervalMilliseconds, batchSize);
}

/**
 * Status returns an atomic snapshot of the event generator state.
 * @returns {$CancellablePromise<$models.EventSpikeStatus>}
 */
export function Status() {
    return $Call.ByID(938765502).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Stop cancels the active generator and returns its final counters.
 * @returns {$CancellablePromise<$models.EventSpikeStatus>}
 */
export function Stop() {
    return $Call.ByID(4074363420).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.EventSpikeStatus.createFrom;
