// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExitGuardService 对外暴露未保存状态登记与确认后的退出续行。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConfirmQuit 放行一次原生退出请求,并在绑定响应送达后继续关闭流程。
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ConfirmQuit() {
    return $Call.ByID(1403839512).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetDirty 登记或清除一个编辑器或表单的未保存状态。
 * @param {string} owner
 * @param {string} label
 * @param {boolean} dirty
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function SetDirty(owner, label, dirty) {
    return $Call.ByID(3226226177, owner, label, dirty).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * State 返回当前的未保存内容登记表。
 * @returns {$CancellablePromise<$models.ExitGuardStateResult>}
 */
export function State() {
    return $Call.ByID(732990678).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.ExitGuardStateResult.createFrom;
