// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExitGuardService exposes dirty-state registration and confirmed quit continuation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConfirmQuit authorizes one native quit request and resumes shutdown after the binding response is delivered.
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ConfirmQuit() {
    return $Call.ByID(1403839512).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetDirty registers or clears one editor or form dirty state.
 * @param {string} owner
 * @param {string} label
 * @param {boolean} dirty
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function SetDirty(owner, label, dirty) {
    return $Call.ByID(3226226177, owner, label, dirty).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * State returns the current unsaved-content registry.
 * @returns {$CancellablePromise<$models.ExitGuardStateResult>}
 */
export function State() {
    return $Call.ByID(732990678).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.ExitGuardStateResult.createFrom;
