// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService exposes bounded remote Linux file operations over existing SSH Sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Chmod applies one validated octal mode to a remote entry.
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @param {string} mode
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Chmod(sshSessionID, path, currentDirectory, mode) {
    return $Call.ByID(1173484501, sshSessionID, path, currentDirectory, mode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateDirectory creates one remote directory.
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function CreateDirectory(sshSessionID, path, currentDirectory) {
    return $Call.ByID(2904998355, sshSessionID, path, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateFile creates one empty remote file.
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function CreateFile(sshSessionID, path, currentDirectory) {
    return $Call.ByID(601416070, sshSessionID, path, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Delete removes one remote entry after dangerous-path checks.
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @param {boolean} recursive
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Delete(sshSessionID, path, currentDirectory, recursive) {
    return $Call.ByID(3405418671, sshSessionID, path, currentDirectory, recursive).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ExtractZIP starts safe extraction of one remote ZIP into a new remote directory.
 * @param {string} sshSessionID
 * @param {string} archivePath
 * @param {string} destinationPath
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.FileTransferResult>}
 */
export function ExtractZIP(sshSessionID, archivePath, destinationPath, currentDirectory) {
    return $Call.ByID(2838065844, sshSessionID, archivePath, destinationPath, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * List returns one normalized remote directory.
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.FileResult>}
 */
export function List(sshSessionID, path, currentDirectory) {
    return $Call.ByID(2876212588, sshSessionID, path, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * PickAndDownload opens the native save dialog and starts an SSH stdout download Operation.
 * @param {string} sshSessionID
 * @param {string} remotePath
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.FileTransferResult>}
 */
export function PickAndDownload(sshSessionID, remotePath, currentDirectory) {
    return $Call.ByID(4291912326, sshSessionID, remotePath, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PickAndUpload opens the native multi-file picker and starts an SSH stdin upload Operation.
 * @param {string} sshSessionID
 * @param {string} remoteDirectory
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.FileTransferResult>}
 */
export function PickAndUpload(sshSessionID, remoteDirectory, currentDirectory) {
    return $Call.ByID(885289747, sshSessionID, remoteDirectory, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ReadText returns one bounded UTF-8 remote document.
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.FileResult>}
 */
export function ReadText(sshSessionID, path, currentDirectory) {
    return $Call.ByID(3610466431, sshSessionID, path, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Rename moves one remote entry without replacing an existing target.
 * @param {string} sshSessionID
 * @param {string} sourcePath
 * @param {string} targetPath
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Rename(sshSessionID, sourcePath, targetPath, currentDirectory) {
    return $Call.ByID(3116443846, sshSessionID, sourcePath, targetPath, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveText conflict-checks and atomically replaces one existing remote document.
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @param {string} content
 * @param {string} expectedVersion
 * @returns {$CancellablePromise<$models.FileResult>}
 */
export function SaveText(sshSessionID, path, currentDirectory, content, expectedVersion) {
    return $Call.ByID(3855410738, sshSessionID, path, currentDirectory, content, expectedVersion).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SaveTextAs atomically creates one new remote document without replacing an existing path.
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @param {string} content
 * @returns {$CancellablePromise<$models.FileResult>}
 */
export function SaveTextAs(sshSessionID, path, currentDirectory, content) {
    return $Call.ByID(918816014, sshSessionID, path, currentDirectory, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SetApplication attaches the Wails application used for native upload and download path selection.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApplication(app) {
    return $Call.ByID(658290386, app);
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.FileTransferResult.createFrom;
const $$createType2 = $models.FileResult.createFrom;
