// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService 基于已有 SSH Session 暴露有界的远端 Linux 文件操作。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Chmod 对远端条目应用一个已校验的八进制权限。
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @param {string} mode
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Chmod(sshSessionID, path, currentDirectory, mode) {
    return $Call.ByID(1173484501, sshSessionID, path, currentDirectory, mode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateDirectory 创建一个远端目录。
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function CreateDirectory(sshSessionID, path, currentDirectory) {
    return $Call.ByID(2904998355, sshSessionID, path, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateFile 创建一个空的远端文件。
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function CreateFile(sshSessionID, path, currentDirectory) {
    return $Call.ByID(601416070, sshSessionID, path, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Delete 在危险路径检查通过后删除一个远端条目。
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @param {boolean} recursive
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Delete(sshSessionID, path, currentDirectory, recursive) {
    return $Call.ByID(3405418671, sshSessionID, path, currentDirectory, recursive).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ExtractZIP 启动一次安全解压,把远端 ZIP 解到新的远端目录。
 * @param {string} sshSessionID
 * @param {string} archivePath
 * @param {string} destinationPath
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.FileTransferResult>}
 */
export function ExtractZIP(sshSessionID, archivePath, destinationPath, currentDirectory) {
    return $Call.ByID(2838065844, sshSessionID, archivePath, destinationPath, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * List 返回一个规范化后的远端目录。
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.FileResult>}
 */
export function List(sshSessionID, path, currentDirectory) {
    return $Call.ByID(2876212588, sshSessionID, path, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * PickAndDownload 打开原生保存框并启动一次 SSH 标准输出下载任务。
 * @param {string} sshSessionID
 * @param {string} remotePath
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.FileTransferResult>}
 */
export function PickAndDownload(sshSessionID, remotePath, currentDirectory) {
    return $Call.ByID(4291912326, sshSessionID, remotePath, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PickAndUpload 打开原生多选文件框并启动一次 SSH 标准输入上传任务。
 * @param {string} sshSessionID
 * @param {string} remoteDirectory
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.FileTransferResult>}
 */
export function PickAndUpload(sshSessionID, remoteDirectory, currentDirectory) {
    return $Call.ByID(885289747, sshSessionID, remoteDirectory, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ReadText 返回一份有界的 UTF-8 远端文档。
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.FileResult>}
 */
export function ReadText(sshSessionID, path, currentDirectory) {
    return $Call.ByID(3610466431, sshSessionID, path, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Rename 移动一个远端条目,不覆盖已存在的目标。
 * @param {string} sshSessionID
 * @param {string} sourcePath
 * @param {string} targetPath
 * @param {string} currentDirectory
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Rename(sshSessionID, sourcePath, targetPath, currentDirectory) {
    return $Call.ByID(3116443846, sshSessionID, sourcePath, targetPath, currentDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveText 做冲突检测并原子替换一份已存在的远端文档。
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @param {string} content
 * @param {string} expectedVersion
 * @returns {$CancellablePromise<$models.FileResult>}
 */
export function SaveText(sshSessionID, path, currentDirectory, content, expectedVersion) {
    return $Call.ByID(3855410738, sshSessionID, path, currentDirectory, content, expectedVersion).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SaveTextAs 原子创建一份新的远端文档,不覆盖已存在的路径。
 * @param {string} sshSessionID
 * @param {string} path
 * @param {string} currentDirectory
 * @param {string} content
 * @returns {$CancellablePromise<$models.FileResult>}
 */
export function SaveTextAs(sshSessionID, path, currentDirectory, content) {
    return $Call.ByID(918816014, sshSessionID, path, currentDirectory, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SetApplication 挂接用于原生上传下载路径选择的 Wails 应用实例。
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApplication(app) {
    return $Call.ByID(658290386, app);
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.FileTransferResult.createFrom;
const $$createType2 = $models.FileResult.createFrom;
