// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InstallationService 向 Wails 暴露目录、启动、取消、查询与重试流程。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel 请求取消进行中的安装 Operation。
 * @param {string} operationID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Cancel(operationID) {
    return $Call.ByID(1777557392, operationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Get 返回一个任务及其有序的持久化步骤检查点。
 * @param {string} taskID
 * @returns {$CancellablePromise<$models.InstallationResult>}
 */
export function Get(taskID) {
    return $Call.ByID(2075683950, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListByServer 分页返回某台 Minecraft Server 的安装历史。
 * @param {string} serverID
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.InstallationListResult>}
 */
export function ListByServer(serverID, limit, offset) {
    return $Call.ByID(1175783692, serverID, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListDistributions 返回全部动态注册的首发服务端类型。
 * @returns {$CancellablePromise<$models.ServerDistributionListResult>}
 */
export function ListDistributions() {
    return $Call.ByID(856287237).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ResolveDirectoryConflict 为失败的服务器目录步骤选择备份、改名或取消。
 * @param {string} taskID
 * @param {string} action
 * @param {string} newName
 * @returns {$CancellablePromise<$models.InstallationStartResult>}
 */
export function ResolveDirectoryConflict(taskID, action, newName) {
    return $Call.ByID(145117587, taskID, action, newName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ResolveVersions 返回某个发行版已缓存的目录版本。
 * @param {string} distribution
 * @returns {$CancellablePromise<$models.ServerVersionListResult>}
 */
export function ResolveVersions(distribution) {
    return $Call.ByID(3278447399, distribution).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Retry 启动一个新的 Operation,并保留全部已成功的步骤检查点。
 * @param {string} taskID
 * @returns {$CancellablePromise<$models.InstallationStartResult>}
 */
export function Retry(taskID) {
    return $Call.ByID(1497520720, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Start 先做预检,随后立即返回持久化的任务与 Operation ID。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.InstallationStartResult>}
 */
export function Start(serverID) {
    return $Call.ByID(3576004122, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.InstallationResult.createFrom;
const $$createType2 = $models.InstallationListResult.createFrom;
const $$createType3 = $models.ServerDistributionListResult.createFrom;
const $$createType4 = $models.InstallationStartResult.createFrom;
const $$createType5 = $models.ServerVersionListResult.createFrom;
