// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InstallationService exposes catalog, start, cancel, get, and retry workflows to Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel requests cancellation of the active installation Operation.
 * @param {string} operationID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Cancel(operationID) {
    return $Call.ByID(1777557392, operationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Get returns one task and its ordered durable step checkpoints.
 * @param {string} taskID
 * @returns {$CancellablePromise<$models.InstallationResult>}
 */
export function Get(taskID) {
    return $Call.ByID(2075683950, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListByServer returns paginated installation history for one Minecraft Server.
 * @param {string} serverID
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.InstallationListResult>}
 */
export function ListByServer(serverID, limit, offset) {
    return $Call.ByID(1175783692, serverID, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListDistributions returns all dynamically registered first-release server types.
 * @returns {$CancellablePromise<$models.ServerDistributionListResult>}
 */
export function ListDistributions() {
    return $Call.ByID(856287237).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ResolveDirectoryConflict chooses backup, rename, or cancel for a failed server-directory step.
 * @param {string} taskID
 * @param {string} action
 * @param {string} newName
 * @returns {$CancellablePromise<$models.InstallationStartResult>}
 */
export function ResolveDirectoryConflict(taskID, action, newName) {
    return $Call.ByID(145117587, taskID, action, newName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ResolveVersions returns cached catalog versions for one distribution.
 * @param {string} distribution
 * @returns {$CancellablePromise<$models.ServerVersionListResult>}
 */
export function ResolveVersions(distribution) {
    return $Call.ByID(3278447399, distribution).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Retry starts a new Operation and preserves every successful step checkpoint.
 * @param {string} taskID
 * @returns {$CancellablePromise<$models.InstallationStartResult>}
 */
export function Retry(taskID) {
    return $Call.ByID(1497520720, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Start performs preflight and immediately returns durable task and operation IDs.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.InstallationStartResult>}
 */
export function Start(serverID) {
    return $Call.ByID(3576004122, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.InstallationResult.createFrom;
const $$createType2 = $models.InstallationListResult.createFrom;
const $$createType3 = $models.ServerDistributionListResult.createFrom;
const $$createType4 = $models.InstallationStartResult.createFrom;
const $$createType5 = $models.ServerVersionListResult.createFrom;
