// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JavaRuntimeService exposes discovery, validation, import, default, delete, and recommendation workflows.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete removes an unreferenced registration without deleting remote Java files.
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Delete(id) {
    return $Call.ByID(2990252439, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Discover validates remote managed, JAVA_HOME, PATH, and system candidates.
 * @param {string} sshSessionID
 * @returns {$CancellablePromise<$models.JavaCandidateListResult>}
 */
export function Discover(sshSessionID) {
    return $Call.ByID(3233740299, sshSessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Import validates and registers one remote Java executable.
 * @param {string} sshSessionID
 * @param {string} executablePath
 * @returns {$CancellablePromise<$models.JavaRuntimeResult>}
 */
export function Import(sshSessionID, executablePath) {
    return $Call.ByID(1659243313, sshSessionID, executablePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Install starts a managed remote JDK download, safety validation, extraction, and registration Operation.
 * @param {string} sshSessionID
 * @param {number} majorVersion
 * @param {string} architecture
 * @returns {$CancellablePromise<$models.JavaInstallResult>}
 */
export function Install(sshSessionID, majorVersion, architecture) {
    return $Call.ByID(3884202887, sshSessionID, majorVersion, architecture).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * List returns Java Runtimes filtered by SSH Session and Java major.
 * @param {string} sshSessionID
 * @param {number} majorVersion
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.JavaRuntimeListResult>}
 */
export function List(sshSessionID, majorVersion, limit, offset) {
    return $Call.ByID(1631244292, sshSessionID, majorVersion, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListArtifacts returns approved latest Linux JDK artifacts for one Java major and architecture.
 * @param {number} majorVersion
 * @param {string} architecture
 * @returns {$CancellablePromise<$models.JDKArtifactListResult>}
 */
export function ListArtifacts(majorVersion, architecture) {
    return $Call.ByID(829327431, majorVersion, architecture).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Recommend returns the closest compatible reusable Runtime for a server version.
 * @param {string} sshSessionID
 * @param {string} serverType
 * @param {string} minecraftVersion
 * @returns {$CancellablePromise<$models.JavaRuntimeResult>}
 */
export function Recommend(sshSessionID, serverType, minecraftVersion) {
    return $Call.ByID(2957077078, sshSessionID, serverType, minecraftVersion).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SetDefault selects one Java Runtime as the SSH Session default.
 * @param {string} sshSessionID
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function SetDefault(sshSessionID, id) {
    return $Call.ByID(831395913, sshSessionID, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Validate checks one remote Java executable without persisting it.
 * @param {string} sshSessionID
 * @param {string} executablePath
 * @returns {$CancellablePromise<$models.JavaCandidateListResult>}
 */
export function Validate(sshSessionID, executablePath) {
    return $Call.ByID(1576951514, sshSessionID, executablePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.JavaCandidateListResult.createFrom;
const $$createType2 = $models.JavaRuntimeResult.createFrom;
const $$createType3 = $models.JavaInstallResult.createFrom;
const $$createType4 = $models.JavaRuntimeListResult.createFrom;
const $$createType5 = $models.JDKArtifactListResult.createFrom;
