// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JavaRuntimeService 对外暴露探测、校验、导入、设默认、删除与推荐流程。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除一条无引用的登记,不删除远端 Java 文件。
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Delete(id) {
    return $Call.ByID(2990252439, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Discover 校验远端受管目录、JAVA_HOME、PATH 与系统路径下的候选。
 * @param {string} sshSessionID
 * @returns {$CancellablePromise<$models.JavaCandidateListResult>}
 */
export function Discover(sshSessionID) {
    return $Call.ByID(3233740299, sshSessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Import 校验并登记一个远端 Java 可执行文件。
 * @param {string} sshSessionID
 * @param {string} executablePath
 * @returns {$CancellablePromise<$models.JavaRuntimeResult>}
 */
export function Import(sshSessionID, executablePath) {
    return $Call.ByID(1659243313, sshSessionID, executablePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Install 启动一次受管的远端 JDK 下载、安全校验、解压与登记 Operation。
 * @param {string} sshSessionID
 * @param {number} majorVersion
 * @param {string} architecture
 * @returns {$CancellablePromise<$models.JavaInstallResult>}
 */
export function Install(sshSessionID, majorVersion, architecture) {
    return $Call.ByID(3884202887, sshSessionID, majorVersion, architecture).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * List 按 SSH Session 与 Java 主版本过滤返回 Java 运行时。
 * @param {string} sshSessionID
 * @param {number} majorVersion
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.JavaRuntimeListResult>}
 */
export function List(sshSessionID, majorVersion, limit, offset) {
    return $Call.ByID(1631244292, sshSessionID, majorVersion, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListArtifacts 返回指定 Java 主版本与架构下已核准的最新 Linux JDK 构件。
 * @param {number} majorVersion
 * @param {string} architecture
 * @returns {$CancellablePromise<$models.JDKArtifactListResult>}
 */
export function ListArtifacts(majorVersion, architecture) {
    return $Call.ByID(829327431, majorVersion, architecture).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Recommend 为某个服务端版本返回最接近的可复用兼容运行时。
 * @param {string} sshSessionID
 * @param {string} serverType
 * @param {string} minecraftVersion
 * @returns {$CancellablePromise<$models.JavaRuntimeResult>}
 */
export function Recommend(sshSessionID, serverType, minecraftVersion) {
    return $Call.ByID(2957077078, sshSessionID, serverType, minecraftVersion).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SetDefault 把一条 Java 运行时选为该 SSH Session 的默认项。
 * @param {string} sshSessionID
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function SetDefault(sshSessionID, id) {
    return $Call.ByID(831395913, sshSessionID, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Validate 校验一个远端 Java 可执行文件,不做持久化。
 * @param {string} sshSessionID
 * @param {string} executablePath
 * @returns {$CancellablePromise<$models.JavaCandidateListResult>}
 */
export function Validate(sshSessionID, executablePath) {
    return $Call.ByID(1576951514, sshSessionID, executablePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.JavaCandidateListResult.createFrom;
const $$createType2 = $models.JavaRuntimeResult.createFrom;
const $$createType3 = $models.JavaInstallResult.createFrom;
const $$createType4 = $models.JavaRuntimeListResult.createFrom;
const $$createType5 = $models.JDKArtifactListResult.createFrom;
