// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KnownHostService exposes first-trust, fingerprint-change, history, and deletion workflows.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check returns first_trust, trusted, or changed; changed always requires a separate confirmation.
 * @param {string} hostIdentifier
 * @param {string} fingerprint
 * @returns {$CancellablePromise<$models.HostKeyCheckResult>}
 */
export function Check(hostIdentifier, fingerprint) {
    return $Call.ByID(876302319, hostIdentifier, fingerprint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Delete removes one trusted key record from encrypted SQLite.
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Delete(id) {
    return $Call.ByID(1387875666, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * List returns active and historical host keys for Settings management.
 * @param {string} search
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.KnownHostListResult>}
 */
export function List(search, limit, offset) {
    return $Call.ByID(1279166937, search, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Replace persists a separately confirmed fingerprint change and retains history.
 * @param {$models.ObservedHostKeyInput} input
 * @returns {$CancellablePromise<$models.KnownHostResult>}
 */
export function Replace(input) {
    return $Call.ByID(4156079899, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * TrustFirst persists a user-confirmed first-seen host key.
 * @param {$models.ObservedHostKeyInput} input
 * @returns {$CancellablePromise<$models.KnownHostResult>}
 */
export function TrustFirst(input) {
    return $Call.ByID(3094435673, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.HostKeyCheckResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
const $$createType2 = $models.KnownHostListResult.createFrom;
const $$createType3 = $models.KnownHostResult.createFrom;
