// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KnownHostService 对外暴露首次信任、指纹变更、历史与删除流程。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check 返回 first_trust、trusted 或 changed;changed 一律需要单独确认。
 * @param {string} hostIdentifier
 * @param {string} fingerprint
 * @returns {$CancellablePromise<$models.HostKeyCheckResult>}
 */
export function Check(hostIdentifier, fingerprint) {
    return $Call.ByID(876302319, hostIdentifier, fingerprint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Delete 从加密 SQLite 中删除一条受信任密钥记录。
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Delete(id) {
    return $Call.ByID(1387875666, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * List 返回生效与历史主机密钥,供设置页管理。
 * @param {string} search
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.KnownHostListResult>}
 */
export function List(search, limit, offset) {
    return $Call.ByID(1279166937, search, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Replace 持久化一次单独确认过的指纹变更并保留历史。
 * @param {$models.ObservedHostKeyInput} input
 * @returns {$CancellablePromise<$models.KnownHostResult>}
 */
export function Replace(input) {
    return $Call.ByID(4156079899, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * TrustFirst 持久化一条用户确认过的首见主机密钥。
 * @param {$models.ObservedHostKeyInput} input
 * @returns {$CancellablePromise<$models.KnownHostResult>}
 */
export function TrustFirst(input) {
    return $Call.ByID(3094435673, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.HostKeyCheckResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
const $$createType2 = $models.KnownHostListResult.createFrom;
const $$createType3 = $models.KnownHostResult.createFrom;
