// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LifecycleService 向 Wails 暴露 GetState、Start、Stop、Restart 与 Recover。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetState 先探测远端进程,再返回生命周期状态。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.LifecycleStateResult>}
 */
export function GetState(serverID) {
    return $Call.ByID(2065001673, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Recover 探测全部活动身份并校正 Server 状态。
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Recover() {
    return $Call.ByID(1499124556).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Restart 在同一把 Server 资源锁下执行可跟踪的停止与启动阶段。
 * @param {string} serverID
 * @param {boolean} tmuxInstallConfirmed
 * @returns {$CancellablePromise<$models.LifecycleOperationResult>}
 */
export function Restart(serverID, tmuxInstallConfirmed) {
    return $Call.ByID(3578660899, serverID, tmuxInstallConfirmed).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Start 异步启动 Server 并返回 Operation ID。
 * @param {string} serverID
 * @param {boolean} firewallConfirmed
 * @param {boolean} tmuxInstallConfirmed
 * @returns {$CancellablePromise<$models.LifecycleOperationResult>}
 */
export function Start(serverID, firewallConfirmed, tmuxInstallConfirmed) {
    return $Call.ByID(1612482644, serverID, firewallConfirmed, tmuxInstallConfirmed).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Stop 优雅停止 Server,必要时强制结束整个进程组。
 * @param {string} serverID
 * @param {boolean} force
 * @returns {$CancellablePromise<$models.LifecycleOperationResult>}
 */
export function Stop(serverID, force) {
    return $Call.ByID(713698320, serverID, force).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.LifecycleStateResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
const $$createType2 = $models.LifecycleOperationResult.createFrom;
