// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LifecycleService exposes GetState, Start, Stop, Restart, and Recover to Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetState probes the remote process before returning lifecycle state.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.LifecycleStateResult>}
 */
export function GetState(serverID) {
    return $Call.ByID(2065001673, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Recover probes every active identity and reconciles Server state.
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Recover() {
    return $Call.ByID(1499124556).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Restart performs tracked Stop and Start stages under one Server resource lock.
 * @param {string} serverID
 * @param {boolean} tmuxInstallConfirmed
 * @returns {$CancellablePromise<$models.LifecycleOperationResult>}
 */
export function Restart(serverID, tmuxInstallConfirmed) {
    return $Call.ByID(3578660899, serverID, tmuxInstallConfirmed).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Start starts the Server asynchronously and returns an Operation ID.
 * @param {string} serverID
 * @param {boolean} firewallConfirmed
 * @param {boolean} tmuxInstallConfirmed
 * @returns {$CancellablePromise<$models.LifecycleOperationResult>}
 */
export function Start(serverID, firewallConfirmed, tmuxInstallConfirmed) {
    return $Call.ByID(1612482644, serverID, firewallConfirmed, tmuxInstallConfirmed).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Stop gracefully stops the Server and optionally forces process-group termination.
 * @param {string} serverID
 * @param {boolean} force
 * @returns {$CancellablePromise<$models.LifecycleOperationResult>}
 */
export function Stop(serverID, force) {
    return $Call.ByID(713698320, serverID, force).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.LifecycleStateResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
const $$createType2 = $models.LifecycleOperationResult.createFrom;
