// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoggingService 对外暴露真实的运行期日志路径与安全清理操作。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearArchived 删除已轮转的日志,保留当前进程正在写的文件。
 * @returns {$CancellablePromise<$models.LogStatusResult>}
 */
export function ClearArchived() {
    return $Call.ByID(2551146684).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetStatus 返回当前日志位置与有界的占用量。
 * @returns {$CancellablePromise<$models.LogStatusResult>}
 */
export function GetStatus() {
    return $Call.ByID(888907513).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OpenDirectory 打开真实的运行期日志目录。
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function OpenDirectory() {
    return $Call.ByID(1806556012).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.LogStatusResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
