// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoggingService exposes actual runtime log paths and safe cleanup actions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearArchived removes rotated logs while preserving the active process file.
 * @returns {$CancellablePromise<$models.LogStatusResult>}
 */
export function ClearArchived() {
    return $Call.ByID(2551146684).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetStatus returns the active log location and bounded usage.
 * @returns {$CancellablePromise<$models.LogStatusResult>}
 */
export function GetStatus() {
    return $Call.ByID(888907513).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OpenDirectory opens the actual runtime log directory.
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function OpenDirectory() {
    return $Call.ByID(1806556012).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.LogStatusResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
