// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MetricService 对外暴露写入、最新值、历史、维护与容量操作。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Ingest 原子接收一个有界的 Metric 批次。
 * @param {model$0.MetricSample[]} samples
 * @returns {$CancellablePromise<$models.MetricIngestServiceResult>}
 */
export function Ingest(samples) {
    return $Call.ByID(982920090, samples).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Latest 返回某台 Server 全部可用指标的最新值。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.MetricLatestServiceResult>}
 */
export function Latest(serverID) {
    return $Call.ByID(3359018541, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Query 返回原始、分钟或小时序列,并显式标注缺失数据点。
 * @param {model$0.MetricQuery} query
 * @returns {$CancellablePromise<$models.MetricQueryServiceResult>}
 */
export function Query(query) {
    return $Call.ByID(66926506, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RunMaintenance 触发一轮有界的降采样与保留清理。
 * @returns {$CancellablePromise<$models.MetricMaintenanceServiceResult>}
 */
export function RunMaintenance() {
    return $Call.ByID(246258950).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * StorageStatus 返回数据库容量与磁盘可用空间状态。
 * @returns {$CancellablePromise<$models.MetricStorageServiceResult>}
 */
export function StorageStatus() {
    return $Call.ByID(3568410981).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.MetricIngestServiceResult.createFrom;
const $$createType1 = $models.MetricLatestServiceResult.createFrom;
const $$createType2 = $models.MetricQueryServiceResult.createFrom;
const $$createType3 = $models.MetricMaintenanceServiceResult.createFrom;
const $$createType4 = $models.MetricStorageServiceResult.createFrom;
