// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MetricService exposes stage 10 ingest, latest, history, maintenance, and capacity operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Ingest atomically accepts one bounded Metric batch.
 * @param {model$0.MetricSample[]} samples
 * @returns {$CancellablePromise<$models.MetricIngestServiceResult>}
 */
export function Ingest(samples) {
    return $Call.ByID(982920090, samples).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Latest returns every available latest Metric for one Server.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.MetricLatestServiceResult>}
 */
export function Latest(serverID) {
    return $Call.ByID(3359018541, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Query returns raw, minute, or hour series with explicit missing-data points.
 * @param {model$0.MetricQuery} query
 * @returns {$CancellablePromise<$models.MetricQueryServiceResult>}
 */
export function Query(query) {
    return $Call.ByID(66926506, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RunMaintenance triggers one bounded rollup and retention pass.
 * @returns {$CancellablePromise<$models.MetricMaintenanceServiceResult>}
 */
export function RunMaintenance() {
    return $Call.ByID(246258950).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * StorageStatus returns database capacity and free-disk status.
 * @returns {$CancellablePromise<$models.MetricStorageServiceResult>}
 */
export function StorageStatus() {
    return $Call.ByID(3568410981).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.MetricIngestServiceResult.createFrom;
const $$createType1 = $models.MetricLatestServiceResult.createFrom;
const $$createType2 = $models.MetricQueryServiceResult.createFrom;
const $$createType3 = $models.MetricMaintenanceServiceResult.createFrom;
const $$createType4 = $models.MetricStorageServiceResult.createFrom;
