// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MinecraftServerService 对外暴露加密元数据的增删改查与删除保护。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../service/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create 持久化一条绑定 SSH、处于创建中状态的 Server 记录。
 * @param {$models.MinecraftServerInput} input
 * @returns {$CancellablePromise<$models.MinecraftServerResult>}
 */
export function Create(input) {
    return $Call.ByID(553592384, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateBackup 启动一次受管的远端 tar.gz 备份 Operation。
 * @param {string} id
 * @returns {$CancellablePromise<$models.MinecraftServerOperationResult>}
 */
export function CreateBackup(id) {
    return $Call.ByID(3764256078, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Get 返回一台 Server,可选择是否包含已软删除记录。
 * @param {string} id
 * @param {boolean} includeDeleted
 * @returns {$CancellablePromise<$models.MinecraftServerResult>}
 */
export function Get(id, includeDeleted) {
    return $Call.ByID(1014591408, id, includeDeleted).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * HardDeleteRegistration 在名称与路径精确确认后,仅删除元数据。
 * @param {string} id
 * @param {string} confirmedName
 * @param {string} confirmedPath
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function HardDeleteRegistration(id, confirmedName, confirmedPath) {
    return $Call.ByID(1265191687, id, confirmedName, confirmedPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * HardDeleteRemote 在精确确认后启动远端目录与登记的永久删除。
 * @param {string} id
 * @param {string} confirmedName
 * @param {string} confirmedPath
 * @returns {$CancellablePromise<$models.MinecraftServerOperationResult>}
 */
export function HardDeleteRemote(id, confirmedName, confirmedPath) {
    return $Call.ByID(3230884460, id, confirmedName, confirmedPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ImportRemote 登记已探测的远端文件,不改动原目录。
 * @param {$models.MinecraftServerInput} input
 * @returns {$CancellablePromise<$models.MinecraftServerResult>}
 */
export function ImportRemote(input) {
    return $Call.ByID(3960696879, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * InspectInstallationStatus 把远端文件与 Server 元数据、最近的安装检查点做比对。
 * @param {string} id
 * @returns {$CancellablePromise<$models.ServerInstallationStatusResult>}
 */
export function InspectInstallationStatus(id) {
    return $Call.ByID(3881968322, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * InspectRemote 在导入已有远端 Server 之前执行只读校验。
 * @param {string} sshSessionID
 * @param {string} remotePath
 * @returns {$CancellablePromise<$models.RemoteServerInspectionResult>}
 */
export function InspectRemote(sshSessionID, remotePath) {
    return $Call.ByID(3971433358, sshSessionID, remotePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * List 按过滤条件返回 Server 列表。
 * @param {string} search
 * @param {string} sshSessionID
 * @param {string} group
 * @param {string} tag
 * @param {string} state
 * @param {boolean} includeDeleted
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.MinecraftServerListResult>}
 */
export function List(search, sshSessionID, group, tag, state, includeDeleted, limit, offset) {
    return $Call.ByID(2456142620, search, sshSessionID, group, tag, state, includeDeleted, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListBackups 返回某台 Server 由 MineOps 管理的远端归档。
 * @param {string} id
 * @returns {$CancellablePromise<$models.ServerBackupListResult>}
 */
export function ListBackups(id) {
    return $Call.ByID(3920473251, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListPropertyBackups 返回保存前保留的 server.properties 历史版本。
 * @param {string} id
 * @returns {$CancellablePromise<$models.ServerPropertiesBackupListResult>}
 */
export function ListPropertyBackups(id) {
    return $Call.ByID(3444867020, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ReadProperties 返回 server.properties 的原文与结构化状态。
 * @param {string} id
 * @returns {$CancellablePromise<$models.ServerPropertiesResult>}
 */
export function ReadProperties(id) {
    return $Call.ByID(328156269, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * Restore 把已软删除的 Server 恢复为已停止状态。
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Restore(id) {
    return $Call.ByID(1267508830, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RestoreBackup 启动安全校验与 Server 目录的原子恢复。
 * @param {string} id
 * @param {string} backupPath
 * @returns {$CancellablePromise<$models.MinecraftServerOperationResult>}
 */
export function RestoreBackup(id, backupPath) {
    return $Call.ByID(67109016, id, backupPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RestorePropertyBackup 校验当前版本标识后恢复一个保留的历史版本。
 * @param {string} id
 * @param {string} backupPath
 * @param {string} expectedVersion
 * @param {boolean} firewallConfirmed
 * @returns {$CancellablePromise<$models.ServerPropertiesResult>}
 */
export function RestorePropertyBackup(id, backupPath, expectedVersion, firewallConfirmed) {
    return $Call.ByID(1587810793, id, backupPath, expectedVersion, firewallConfirmed).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * SaveProperties 按原文或结构化方式保存,带冲突检测并保留备份。
 * @param {string} id
 * @param {string} mode
 * @param {string} rawContent
 * @param {string} expectedVersion
 * @param {service$0.ServerPropertyUpdate[]} updates
 * @param {boolean} firewallConfirmed
 * @returns {$CancellablePromise<$models.ServerPropertiesResult>}
 */
export function SaveProperties(id, mode, rawContent, expectedVersion, updates, firewallConfirmed) {
    return $Call.ByID(1995887096, id, mode, rawContent, expectedVersion, updates, firewallConfirmed).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * SoftDelete 保留远端目录,仅把元数据标记为已删除。
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function SoftDelete(id) {
    return $Call.ByID(2823854271, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Update 只改元数据,不移动远端目录也不改 SSH 绑定。
 * @param {string} id
 * @param {$models.MinecraftServerInput} input
 * @returns {$CancellablePromise<$models.MinecraftServerResult>}
 */
export function Update(id, input) {
    return $Call.ByID(1491531221, id, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.MinecraftServerResult.createFrom;
const $$createType1 = $models.MinecraftServerOperationResult.createFrom;
const $$createType2 = $models.ActionResult.createFrom;
const $$createType3 = $models.ServerInstallationStatusResult.createFrom;
const $$createType4 = $models.RemoteServerInspectionResult.createFrom;
const $$createType5 = $models.MinecraftServerListResult.createFrom;
const $$createType6 = $models.ServerBackupListResult.createFrom;
const $$createType7 = $models.ServerPropertiesBackupListResult.createFrom;
const $$createType8 = $models.ServerPropertiesResult.createFrom;
