// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MinecraftServerService exposes encrypted metadata CRUD and deletion protection.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../service/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create persists a new SSH-bound Creating Server record.
 * @param {$models.MinecraftServerInput} input
 * @returns {$CancellablePromise<$models.MinecraftServerResult>}
 */
export function Create(input) {
    return $Call.ByID(553592384, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateBackup starts a managed remote tar.gz backup Operation.
 * @param {string} id
 * @returns {$CancellablePromise<$models.MinecraftServerOperationResult>}
 */
export function CreateBackup(id) {
    return $Call.ByID(3764256078, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Get returns one Server, optionally including soft-deleted records.
 * @param {string} id
 * @param {boolean} includeDeleted
 * @returns {$CancellablePromise<$models.MinecraftServerResult>}
 */
export function Get(id, includeDeleted) {
    return $Call.ByID(1014591408, id, includeDeleted).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * HardDeleteRegistration removes only metadata after exact Name and Path confirmation.
 * @param {string} id
 * @param {string} confirmedName
 * @param {string} confirmedPath
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function HardDeleteRegistration(id, confirmedName, confirmedPath) {
    return $Call.ByID(1265191687, id, confirmedName, confirmedPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * HardDeleteRemote starts permanent remote directory and registration deletion after exact confirmation.
 * @param {string} id
 * @param {string} confirmedName
 * @param {string} confirmedPath
 * @returns {$CancellablePromise<$models.MinecraftServerOperationResult>}
 */
export function HardDeleteRemote(id, confirmedName, confirmedPath) {
    return $Call.ByID(3230884460, id, confirmedName, confirmedPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ImportRemote registers inspected remote files without modifying the original directory.
 * @param {$models.MinecraftServerInput} input
 * @returns {$CancellablePromise<$models.MinecraftServerResult>}
 */
export function ImportRemote(input) {
    return $Call.ByID(3960696879, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * InspectInstallationStatus compares remote files with Server metadata and the latest Installation checkpoints.
 * @param {string} id
 * @returns {$CancellablePromise<$models.ServerInstallationStatusResult>}
 */
export function InspectInstallationStatus(id) {
    return $Call.ByID(3881968322, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * InspectRemote performs read-only validation before importing an existing remote Server.
 * @param {string} sshSessionID
 * @param {string} remotePath
 * @returns {$CancellablePromise<$models.RemoteServerInspectionResult>}
 */
export function InspectRemote(sshSessionID, remotePath) {
    return $Call.ByID(3971433358, sshSessionID, remotePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * List returns filtered Server rows.
 * @param {string} search
 * @param {string} sshSessionID
 * @param {string} group
 * @param {string} tag
 * @param {string} state
 * @param {boolean} includeDeleted
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.MinecraftServerListResult>}
 */
export function List(search, sshSessionID, group, tag, state, includeDeleted, limit, offset) {
    return $Call.ByID(2456142620, search, sshSessionID, group, tag, state, includeDeleted, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListBackups returns MineOps-managed remote archives for one Server.
 * @param {string} id
 * @returns {$CancellablePromise<$models.ServerBackupListResult>}
 */
export function ListBackups(id) {
    return $Call.ByID(3920473251, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListPropertyBackups returns retained pre-save server.properties revisions.
 * @param {string} id
 * @returns {$CancellablePromise<$models.ServerPropertiesBackupListResult>}
 */
export function ListPropertyBackups(id) {
    return $Call.ByID(3444867020, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ReadProperties returns raw and structured server.properties state.
 * @param {string} id
 * @returns {$CancellablePromise<$models.ServerPropertiesResult>}
 */
export function ReadProperties(id) {
    return $Call.ByID(328156269, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * Restore restores a soft-deleted Server to Stopped state.
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Restore(id) {
    return $Call.ByID(1267508830, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RestoreBackup starts safe validation and atomic Server directory restoration.
 * @param {string} id
 * @param {string} backupPath
 * @returns {$CancellablePromise<$models.MinecraftServerOperationResult>}
 */
export function RestoreBackup(id, backupPath) {
    return $Call.ByID(67109016, id, backupPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RestorePropertyBackup restores one retained revision after checking the current version token.
 * @param {string} id
 * @param {string} backupPath
 * @param {string} expectedVersion
 * @param {boolean} firewallConfirmed
 * @returns {$CancellablePromise<$models.ServerPropertiesResult>}
 */
export function RestorePropertyBackup(id, backupPath, expectedVersion, firewallConfirmed) {
    return $Call.ByID(1587810793, id, backupPath, expectedVersion, firewallConfirmed).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * SaveProperties saves raw content or structured updates with conflict detection and retained backups.
 * @param {string} id
 * @param {string} mode
 * @param {string} rawContent
 * @param {string} expectedVersion
 * @param {service$0.ServerPropertyUpdate[]} updates
 * @param {boolean} firewallConfirmed
 * @returns {$CancellablePromise<$models.ServerPropertiesResult>}
 */
export function SaveProperties(id, mode, rawContent, expectedVersion, updates, firewallConfirmed) {
    return $Call.ByID(1995887096, id, mode, rawContent, expectedVersion, updates, firewallConfirmed).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * SoftDelete preserves the remote directory and marks metadata Deleted.
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function SoftDelete(id) {
    return $Call.ByID(2823854271, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Update changes metadata without moving the remote directory or changing SSH binding.
 * @param {string} id
 * @param {$models.MinecraftServerInput} input
 * @returns {$CancellablePromise<$models.MinecraftServerResult>}
 */
export function Update(id, input) {
    return $Call.ByID(1491531221, id, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.MinecraftServerResult.createFrom;
const $$createType1 = $models.MinecraftServerOperationResult.createFrom;
const $$createType2 = $models.ActionResult.createFrom;
const $$createType3 = $models.ServerInstallationStatusResult.createFrom;
const $$createType4 = $models.RemoteServerInspectionResult.createFrom;
const $$createType5 = $models.MinecraftServerListResult.createFrom;
const $$createType6 = $models.ServerBackupListResult.createFrom;
const $$createType7 = $models.ServerPropertiesBackupListResult.createFrom;
const $$createType8 = $models.ServerPropertiesResult.createFrom;
