// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MonitoringService 对外暴露统一的监控查询边界。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearHistory 删除所选 Server 的全部持久化 Metric 数据。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ClearHistory(serverID) {
    return $Call.ByID(3962119407, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CollectNow 为所选 Server 立即触发一次 SSH 拉取采集。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function CollectNow(serverID) {
    return $Call.ByID(2320845482, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Overview 返回采集状态、最新指标、Spark 状态、活跃告警与采集异常。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.MonitoringOverviewResult>}
 */
export function Overview(serverID) {
    return $Call.ByID(2634109643, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Pause 停止所选 Server 后续的自动 Metric 采集。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Pause(serverID) {
    return $Call.ByID(841758346, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Query 通过统一门面返回走索引的指标历史,并显式标注空洞。
 * @param {model$0.MetricQuery} query
 * @returns {$CancellablePromise<$models.MetricQueryServiceResult>}
 */
export function Query(query) {
    return $Call.ByID(1950502124, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Resume 恢复所选 Server 的自动 Metric 采集。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Resume(serverID) {
    return $Call.ByID(3266393739, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.MonitoringOverviewResult.createFrom;
const $$createType2 = $models.MetricQueryServiceResult.createFrom;
