// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MonitoringService exposes the unified stage 12 monitoring query boundary.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearHistory deletes every persisted Metric row for the selected Server.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ClearHistory(serverID) {
    return $Call.ByID(3962119407, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CollectNow triggers one immediate SSH pull collection pass for the selected Server.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function CollectNow(serverID) {
    return $Call.ByID(2320845482, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Overview returns Agent state, latest metrics, Spark state, active alerts, and collection issues.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.MonitoringOverviewResult>}
 */
export function Overview(serverID) {
    return $Call.ByID(2634109643, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Pause stops future automatic Metric collection passes for the selected Server.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Pause(serverID) {
    return $Call.ByID(841758346, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Query returns indexed metric history with explicit gaps through the unified facade.
 * @param {model$0.MetricQuery} query
 * @returns {$CancellablePromise<$models.MetricQueryServiceResult>}
 */
export function Query(query) {
    return $Call.ByID(1950502124, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Resume restores automatic Metric collection for the selected Server.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Resume(serverID) {
    return $Call.ByID(3266393739, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.MonitoringOverviewResult.createFrom;
const $$createType2 = $models.MetricQueryServiceResult.createFrom;
