// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OperationService 通过显式 DTO 暴露持久化 Operation 的查询、取消与终态历史维护。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel 幂等地请求取消一条活动 Operation。
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Cancel(id) {
    return $Call.ByID(2626701603, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ClearHistory 删除全部终态 Operation,保留进行中的工作。
 * @returns {$CancellablePromise<$models.OperationMutationResult>}
 */
export function ClearHistory() {
    return $Call.ByID(216648058).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteHistory 删除一条已完成、失败或已取消的 Operation。
 * @param {string} id
 * @returns {$CancellablePromise<$models.OperationMutationResult>}
 */
export function DeleteHistory(id) {
    return $Call.ByID(176994210, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Get 按 ID 返回一条持久化 Operation。
 * @param {string} id
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function Get(id) {
    return $Call.ByID(939636271, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListActive 返回待执行与运行中的 Operation,可按目标 ID 过滤。
 * @param {string} targetID
 * @returns {$CancellablePromise<$models.OperationListResult>}
 */
export function ListActive(targetID) {
    return $Call.ByID(414456235, targetID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListHistory 分页返回持久化的 Operation 历史。
 * @param {string} targetID
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.OperationListResult>}
 */
export function ListHistory(targetID, limit, offset) {
    return $Call.ByID(576070683, targetID, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.OperationMutationResult.createFrom;
const $$createType2 = $models.OperationResult.createFrom;
const $$createType3 = $models.OperationListResult.createFrom;
