// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OperationService exposes durable Operation queries, cancellation, and terminal-history maintenance through explicit DTOs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel requests idempotent cancellation of an active Operation.
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Cancel(id) {
    return $Call.ByID(2626701603, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ClearHistory deletes every terminal Operation while preserving active work.
 * @returns {$CancellablePromise<$models.OperationMutationResult>}
 */
export function ClearHistory() {
    return $Call.ByID(216648058).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteHistory deletes one completed, failed, or cancelled Operation.
 * @param {string} id
 * @returns {$CancellablePromise<$models.OperationMutationResult>}
 */
export function DeleteHistory(id) {
    return $Call.ByID(176994210, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Get returns one durable Operation by ID.
 * @param {string} id
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function Get(id) {
    return $Call.ByID(939636271, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListActive returns pending and running Operations, optionally filtered by target ID.
 * @param {string} targetID
 * @returns {$CancellablePromise<$models.OperationListResult>}
 */
export function ListActive(targetID) {
    return $Call.ByID(414456235, targetID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListHistory returns paginated durable Operation history.
 * @param {string} targetID
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.OperationListResult>}
 */
export function ListHistory(targetID, limit, offset) {
    return $Call.ByID(576070683, targetID, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.OperationMutationResult.createFrom;
const $$createType2 = $models.OperationResult.createFrom;
const $$createType3 = $models.OperationListResult.createFrom;
