// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PerformanceService exposes Spark detection, install, collection, reports, and correlated metrics.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CollectSnapshot collects and persists one locked TPS/MSPT sample.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.SparkSnapshotServiceResult>}
 */
export function CollectSnapshot(serverID) {
    return $Call.ByID(1228976344, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteReport 删除一条已结束的 Spark 报告记录。
 * @param {string} reportID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function DeleteReport(reportID) {
    return $Call.ByID(1283363723, reportID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Install executes one explicitly confirmed Spark install or upgrade.
 * @param {string} serverID
 * @param {string} planDigest
 * @param {boolean} confirmed
 * @returns {$CancellablePromise<$models.SparkInstallServiceResult>}
 */
export function Install(serverID, planDigest, confirmed) {
    return $Call.ByID(2021762873, serverID, planDigest, confirmed).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Overview returns bounded Spark, report, Agent, and related metric state.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.PerformanceOverviewResult>}
 */
export function Overview(serverID) {
    return $Call.ByID(2276310297, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * PlanInstall computes the approved source, checksum, target, backup, and restart impact.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.SparkInstallPlanServiceResult>}
 */
export function PlanInstall(serverID) {
    return $Call.ByID(1141424052, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Probe detects Spark installation, compatibility, permissions, and collection method.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.SparkCapabilityServiceResult>}
 */
export function Probe(serverID) {
    return $Call.ByID(3127105540, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Rollback restores the latest recorded Spark backup after explicit confirmation.
 * @param {string} serverID
 * @param {boolean} confirmed
 * @returns {$CancellablePromise<$models.SparkCapabilityServiceResult>}
 */
export function Rollback(serverID, confirmed) {
    return $Call.ByID(2798694290, serverID, confirmed).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StartHealthReport starts one privacy-confirmed health report Operation.
 * @param {string} serverID
 * @param {boolean} privacyAcknowledged
 * @returns {$CancellablePromise<$models.SparkReportServiceResult>}
 */
export function StartHealthReport(serverID, privacyAcknowledged) {
    return $Call.ByID(3544674578, serverID, privacyAcknowledged).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * StartProfiler starts one explicit-duration privacy-confirmed profiler Operation.
 * @param {string} serverID
 * @param {number} durationSeconds
 * @param {boolean} privacyAcknowledged
 * @returns {$CancellablePromise<$models.SparkReportServiceResult>}
 */
export function StartProfiler(serverID, durationSeconds, privacyAcknowledged) {
    return $Call.ByID(2191974135, serverID, durationSeconds, privacyAcknowledged).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SparkSnapshotServiceResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
const $$createType2 = $models.SparkInstallServiceResult.createFrom;
const $$createType3 = $models.PerformanceOverviewResult.createFrom;
const $$createType4 = $models.SparkInstallPlanServiceResult.createFrom;
const $$createType5 = $models.SparkCapabilityServiceResult.createFrom;
const $$createType6 = $models.SparkReportServiceResult.createFrom;
