// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PerformanceService 对外暴露 Spark 探测、安装、采集、报告与关联指标。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CollectSnapshot 采集并持久化一条锁定的 TPS/MSPT 样本。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.SparkSnapshotServiceResult>}
 */
export function CollectSnapshot(serverID) {
    return $Call.ByID(1228976344, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteReport 删除一条已结束的 Spark 报告记录。
 * @param {string} reportID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function DeleteReport(reportID) {
    return $Call.ByID(1283363723, reportID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Install 执行一次显式确认过的 Spark 安装或升级。
 * @param {string} serverID
 * @param {string} planDigest
 * @param {boolean} confirmed
 * @returns {$CancellablePromise<$models.SparkInstallServiceResult>}
 */
export function Install(serverID, planDigest, confirmed) {
    return $Call.ByID(2021762873, serverID, planDigest, confirmed).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Overview 返回有界的 Spark、报告、采集与相关指标状态。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.PerformanceOverviewResult>}
 */
export function Overview(serverID) {
    return $Call.ByID(2276310297, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * PlanInstall 计算已核准的来源、校验和、目标路径、备份与重启影响。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.SparkInstallPlanServiceResult>}
 */
export function PlanInstall(serverID) {
    return $Call.ByID(1141424052, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Probe 探测 Spark 的安装情况、兼容性、权限与采集方式。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.SparkCapabilityServiceResult>}
 */
export function Probe(serverID) {
    return $Call.ByID(3127105540, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Rollback 在显式确认后恢复最近一次记录的 Spark 备份。
 * @param {string} serverID
 * @param {boolean} confirmed
 * @returns {$CancellablePromise<$models.SparkCapabilityServiceResult>}
 */
export function Rollback(serverID, confirmed) {
    return $Call.ByID(2798694290, serverID, confirmed).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StartHealthReport 启动一次已确认隐私风险的健康报告 Operation。
 * @param {string} serverID
 * @param {boolean} privacyAcknowledged
 * @returns {$CancellablePromise<$models.SparkReportServiceResult>}
 */
export function StartHealthReport(serverID, privacyAcknowledged) {
    return $Call.ByID(3544674578, serverID, privacyAcknowledged).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * StartProfiler 启动一次时长显式、已确认隐私风险的性能分析 Operation。
 * @param {string} serverID
 * @param {number} durationSeconds
 * @param {boolean} privacyAcknowledged
 * @returns {$CancellablePromise<$models.SparkReportServiceResult>}
 */
export function StartProfiler(serverID, durationSeconds, privacyAcknowledged) {
    return $Call.ByID(2191974135, serverID, durationSeconds, privacyAcknowledged).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SparkSnapshotServiceResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
const $$createType2 = $models.SparkInstallServiceResult.createFrom;
const $$createType3 = $models.PerformanceOverviewResult.createFrom;
const $$createType4 = $models.SparkInstallPlanServiceResult.createFrom;
const $$createType5 = $models.SparkCapabilityServiceResult.createFrom;
const $$createType6 = $models.SparkReportServiceResult.createFrom;
