// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlayerService 对外暴露统一的玩家查询、同步与管理操作。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddWhitelist 把玩家加入 Minecraft 白名单。
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function AddWhitelist(input) {
    return $Call.ByID(3056365923, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Ban 封禁一名玩家,原因可选。
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function Ban(input) {
    return $Call.ByID(860089920, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Detail 返回一份统一的玩家总览。
 * @param {string} serverID
 * @param {string} playerID
 * @returns {$CancellablePromise<$models.PlayerDetailServiceResult>}
 */
export function Detail(serverID, playerID) {
    return $Call.ByID(4009081994, serverID, playerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GrantOperator 授予 Minecraft 管理员权限。
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function GrantOperator(input) {
    return $Call.ByID(1251205923, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Kick 断开一名当前在线玩家的连接。
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function Kick(input) {
    return $Call.ByID(3438247577, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * List 返回一页有界的统一玩家数据。
 * @param {model$0.PlayerQuery} query
 * @returns {$CancellablePromise<$models.PlayerListServiceResult>}
 */
export function List(query) {
    return $Call.ByID(377247907, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Pardon 解除一名玩家的封禁。
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function Pardon(input) {
    return $Call.ByID(1535099295, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RecentSessions 按时间倒序返回有界的近期会话。
 * @param {model$0.PlayerSessionQuery} query
 * @returns {$CancellablePromise<$models.PlayerSessionsServiceResult>}
 */
export function RecentSessions(query) {
    return $Call.ByID(236331717, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RefreshDirectory 同步 Minecraft 权威玩家名录文件。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.PlayerListServiceResult>}
 */
export function RefreshDirectory(serverID) {
    return $Call.ByID(1797281797, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RemoveWhitelist 把玩家移出 Minecraft 白名单。
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function RemoveWhitelist(input) {
    return $Call.ByID(3668468872, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RevokeOperator 撤销 Minecraft 管理员权限。
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function RevokeOperator(input) {
    return $Call.ByID(3185783497, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SynchronizeActivity 认领并应用远端待处理的玩家活动证据。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.PlayerListServiceResult>}
 */
export function SynchronizeActivity(serverID) {
    return $Call.ByID(3702454978, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.PlayerActionServiceResult.createFrom;
const $$createType1 = $models.PlayerDetailServiceResult.createFrom;
const $$createType2 = $models.PlayerListServiceResult.createFrom;
const $$createType3 = $models.PlayerSessionsServiceResult.createFrom;
