// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlayerService exposes unified player queries, synchronization, and management actions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddWhitelist adds a player to the Minecraft whitelist.
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function AddWhitelist(input) {
    return $Call.ByID(3056365923, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Ban bans one player with an optional reason.
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function Ban(input) {
    return $Call.ByID(860089920, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Detail returns one unified player overview.
 * @param {string} serverID
 * @param {string} playerID
 * @returns {$CancellablePromise<$models.PlayerDetailServiceResult>}
 */
export function Detail(serverID, playerID) {
    return $Call.ByID(4009081994, serverID, playerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GrantOperator grants Minecraft operator permissions.
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function GrantOperator(input) {
    return $Call.ByID(1251205923, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Kick disconnects one currently online player.
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function Kick(input) {
    return $Call.ByID(3438247577, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * List returns one bounded unified player page.
 * @param {model$0.PlayerQuery} query
 * @returns {$CancellablePromise<$models.PlayerListServiceResult>}
 */
export function List(query) {
    return $Call.ByID(377247907, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Pardon removes one player Ban.
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function Pardon(input) {
    return $Call.ByID(1535099295, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RecentSessions returns bounded recent sessions in newest-first order.
 * @param {model$0.PlayerSessionQuery} query
 * @returns {$CancellablePromise<$models.PlayerSessionsServiceResult>}
 */
export function RecentSessions(query) {
    return $Call.ByID(236331717, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RefreshDirectory synchronizes authoritative Minecraft player files.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.PlayerListServiceResult>}
 */
export function RefreshDirectory(serverID) {
    return $Call.ByID(1797281797, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RemoveWhitelist removes a player from the Minecraft whitelist.
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function RemoveWhitelist(input) {
    return $Call.ByID(3668468872, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RevokeOperator revokes Minecraft operator permissions.
 * @param {model$0.PlayerActionInput} input
 * @returns {$CancellablePromise<$models.PlayerActionServiceResult>}
 */
export function RevokeOperator(input) {
    return $Call.ByID(3185783497, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SynchronizeActivity claims and applies pending remote player evidence.
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.PlayerListServiceResult>}
 */
export function SynchronizeActivity(serverID) {
    return $Call.ByID(3702454978, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.PlayerActionServiceResult.createFrom;
const $$createType1 = $models.PlayerDetailServiceResult.createFrom;
const $$createType2 = $models.PlayerListServiceResult.createFrom;
const $$createType3 = $models.PlayerSessionsServiceResult.createFrom;
