// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes encrypted Settings loading, saving, and category reset.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get returns the immutable current Settings Snapshot.
 * @returns {$CancellablePromise<$models.SettingsResult>}
 */
export function Get() {
    return $Call.ByID(1563844309).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ResetCategory restores one Settings category to its embedded default.
 * @param {string} category
 * @returns {$CancellablePromise<$models.SettingsResult>}
 */
export function ResetCategory(category) {
    return $Call.ByID(2793644674, category).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Save validates and transactionally persists the complete Settings Snapshot.
 * @param {model$0.SettingsSnapshot} snapshot
 * @returns {$CancellablePromise<$models.SettingsResult>}
 */
export function Save(snapshot) {
    return $Call.ByID(2557048438, snapshot).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SettingsResult.createFrom;
