// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SQLCipherSpikeService exposes the encrypted SQLite stage 0 verification.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sqlcipher$0 from "../../infrastructure/sqlcipher/models.js";

/**
 * Run executes the temporary SQLCipher and GORM verification without persisting the key.
 * @returns {$CancellablePromise<sqlcipher$0.SpikeResult>}
 */
export function Run() {
    return $Call.ByID(3551292302).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = sqlcipher$0.SpikeResult.createFrom;
