// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SSHSessionService exposes SSH Session CRUD while keeping secrets out of responses and logs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create persists a new SSH Session and write-only credential input.
 * @param {$models.SSHSessionInput} input
 * @returns {$CancellablePromise<$models.SSHSessionResult>}
 */
export function Create(input) {
    return $Call.ByID(3931252624, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Delete removes an unreferenced SSH Session and its credential.
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Delete(id) {
    return $Call.ByID(1859765231, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Get returns one SSH Session without secret material.
 * @param {string} id
 * @returns {$CancellablePromise<$models.SSHSessionResult>}
 */
export function Get(id) {
    return $Call.ByID(2224075648, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * List returns filtered SSH Sessions without secret material.
 * @param {string} search
 * @param {string} group
 * @param {boolean} favouriteOnly
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.SSHSessionListResult>}
 */
export function List(search, group, favouriteOnly, limit, offset) {
    return $Call.ByID(1098838188, search, group, favouriteOnly, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Preflight authenticates the target through the configured direct or Jump Host route and measures SSH request RTT.
 * @param {string} id
 * @returns {$CancellablePromise<$models.SSHPreflightDTO>}
 */
export function Preflight(id) {
    return $Call.ByID(1686190027, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * TestConnection performs SSH handshake, host-key verification, authentication, and a no-op command.
 * @param {string} id
 * @returns {$CancellablePromise<$models.SSHConnectionTestDTO>}
 */
export function TestConnection(id) {
    return $Call.ByID(2576379224, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * TestInput tests unsaved SSH Session input without persisting draft metadata or credential material.
 * @param {string} id
 * @param {$models.SSHSessionInput} input
 * @returns {$CancellablePromise<$models.SSHConnectionTestDTO>}
 */
export function TestInput(id, input) {
    return $Call.ByID(510888292, id, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Update persists metadata and optional replacement credential input.
 * @param {string} id
 * @param {$models.SSHSessionInput} input
 * @returns {$CancellablePromise<$models.SSHSessionResult>}
 */
export function Update(id, input) {
    return $Call.ByID(243507845, id, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SSHSessionResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
const $$createType2 = $models.SSHSessionListResult.createFrom;
const $$createType3 = $models.SSHPreflightDTO.createFrom;
const $$createType4 = $models.SSHConnectionTestDTO.createFrom;
