// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SSHSessionService 对外暴露 SSH Session 增删改查,并确保密文不进入响应与日志。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create 持久化一个新的 SSH Session 及其只写凭据输入。
 * @param {$models.SSHSessionInput} input
 * @returns {$CancellablePromise<$models.SSHSessionResult>}
 */
export function Create(input) {
    return $Call.ByID(3931252624, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Delete 删除一个无引用的 SSH Session 及其凭据。
 * @param {string} id
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Delete(id) {
    return $Call.ByID(1859765231, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * EnsureHostSpecs 为尚无主机规格的 Session 采集并持久化容量信息。
 * 这是主机规格唯一的采集入口:新建 Session、连接目标变更清空规格、以及迁移前的历史 Session 都走它,
 * 每个 Session 最多采集一次。它与 Create/Update 分离,保证保存操作不会阻塞在一次完整 SSH 往返上。
 * @param {string} id
 * @returns {$CancellablePromise<$models.SSHSessionResult>}
 */
export function EnsureHostSpecs(id) {
    return $Call.ByID(691416428, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Get 返回一个不含密文的 SSH Session。
 * @param {string} id
 * @returns {$CancellablePromise<$models.SSHSessionResult>}
 */
export function Get(id) {
    return $Call.ByID(2224075648, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * List 按过滤条件返回不含密文的 SSH Session。
 * @param {string} search
 * @param {string} group
 * @param {boolean} favouriteOnly
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.SSHSessionListResult>}
 */
export function List(search, group, favouriteOnly, limit, offset) {
    return $Call.ByID(1098838188, search, group, favouriteOnly, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Preflight 按配置的直连或 Jump Host 路由完成认证,并测量 SSH 请求往返时延。
 * @param {string} id
 * @returns {$CancellablePromise<$models.SSHPreflightDTO>}
 */
export function Preflight(id) {
    return $Call.ByID(1686190027, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * TestConnection 执行 SSH 握手、主机密钥校验、认证与一次空操作命令。
 * @param {string} id
 * @returns {$CancellablePromise<$models.SSHConnectionTestDTO>}
 */
export function TestConnection(id) {
    return $Call.ByID(2576379224, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * TestInput 测试未保存的 SSH Session 输入,不持久化草稿元数据与凭据。
 * @param {string} id
 * @param {$models.SSHSessionInput} input
 * @returns {$CancellablePromise<$models.SSHConnectionTestDTO>}
 */
export function TestInput(id, input) {
    return $Call.ByID(510888292, id, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Update 持久化元数据与可选的替换凭据输入。
 * @param {string} id
 * @param {$models.SSHSessionInput} input
 * @returns {$CancellablePromise<$models.SSHSessionResult>}
 */
export function Update(id, input) {
    return $Call.ByID(243507845, id, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SSHSessionResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
const $$createType2 = $models.SSHSessionListResult.createFrom;
const $$createType3 = $models.SSHPreflightDTO.createFrom;
const $$createType4 = $models.SSHConnectionTestDTO.createFrom;
