// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StorageService 对外暴露加密数据库状态、备份、恢复与密钥轮换流程。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelPendingMaintenance 取消全部已排队的下次启动维护任务。
 * @returns {$CancellablePromise<$models.StorageResult>}
 */
export function CancelPendingMaintenance() {
    return $Call.ByID(2502057021).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateBackup 在线创建一份一致的 .mineops-backup 备份文件。
 * @param {string} destination
 * @returns {$CancellablePromise<$models.StorageResult>}
 */
export function CreateBackup(destination) {
    return $Call.ByID(1730586727, destination).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetStatus 返回当前加密数据库状态与已排队的维护任务。
 * @returns {$CancellablePromise<$models.StorageResult>}
 */
export function GetStatus() {
    return $Call.ByID(1120634625).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OpenDataDirectory 打开受控的 MineOps 数据目录。
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function OpenDataDirectory() {
    return $Call.ByID(3855472052).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ScheduleDatabaseReset 排队一次下次启动执行的清空数据库:删除两个库文件与系统密钥。
 * @returns {$CancellablePromise<$models.StorageResult>}
 */
export function ScheduleDatabaseReset() {
    return $Call.ByID(1926244300).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ScheduleKeyRotation 排队一次下次启动执行的 SQLCipher 密钥轮换。
 * @returns {$CancellablePromise<$models.StorageResult>}
 */
export function ScheduleKeyRotation() {
    return $Call.ByID(992267125).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ScheduleRestore 校验备份并排队到下次启动时恢复。
 * @param {string} backupPath
 * @returns {$CancellablePromise<$models.StorageResult>}
 */
export function ScheduleRestore(backupPath) {
    return $Call.ByID(2394135158, backupPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ScheduleVacuum 排队一次下次启动执行的 VACUUM,释放 SQLite 空闲页占用的文件空间。
 * @returns {$CancellablePromise<$models.StorageResult>}
 */
export function ScheduleVacuum() {
    return $Call.ByID(1549216111).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.StorageResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
