// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StorageService exposes encrypted database status, backup, restore, and key-rotation workflows.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelPendingMaintenance clears staged restore, key-rotation, and vacuum work.
 * @returns {$CancellablePromise<$models.StorageResult>}
 */
export function CancelPendingMaintenance() {
    return $Call.ByID(2502057021).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateBackup creates one consistent online .mineops-backup file.
 * @param {string} destination
 * @returns {$CancellablePromise<$models.StorageResult>}
 */
export function CreateBackup(destination) {
    return $Call.ByID(1730586727, destination).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetStatus returns the current encrypted database and pending maintenance state.
 * @returns {$CancellablePromise<$models.StorageResult>}
 */
export function GetStatus() {
    return $Call.ByID(1120634625).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OpenDataDirectory opens the controlled MineOps data directory.
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function OpenDataDirectory() {
    return $Call.ByID(3855472052).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ScheduleKeyRotation stages a SQLCipher key rotation for the next application start.
 * @returns {$CancellablePromise<$models.StorageResult>}
 */
export function ScheduleKeyRotation() {
    return $Call.ByID(992267125).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ScheduleRestore verifies and stages a backup for restoration on the next application start.
 * @param {string} backupPath
 * @returns {$CancellablePromise<$models.StorageResult>}
 */
export function ScheduleRestore(backupPath) {
    return $Call.ByID(2394135158, backupPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ScheduleVacuum stages a VACUUM for the next application start to release SQLite free pages.
 * @returns {$CancellablePromise<$models.StorageResult>}
 */
export function ScheduleVacuum() {
    return $Call.ByID(1549216111).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.StorageResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
