// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService 持有已认证的 SSH PTY、有界输出队列与 Wails 事件。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close 终止一个 PTY 并发出其最终事件。
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Close(sessionID) {
    return $Call.ByID(4057890050, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CloseAll 终止桌面进程持有的全部活动 PTY。
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function CloseAll() {
    return $Call.ByID(2902408921).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Input 向一个 PTY 有序写入 UTF-8 终端输入。
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Input(sessionID, data) {
    return $Call.ByID(1590750906, sessionID, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Open 完成 SSH Session 认证、申请 xterm-256color PTY,并开始有界的输出流转。
 * @param {string} sshSessionID
 * @param {number} columns
 * @param {number} rows
 * @returns {$CancellablePromise<$models.TerminalSessionResult>}
 */
export function Open(sshSessionID, columns, rows) {
    return $Call.ByID(684388806, sshSessionID, columns, rows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Resize 应用远端窗口尺寸变更请求并更新会话尺寸。
 * @param {string} sessionID
 * @param {number} columns
 * @param {number} rows
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Resize(sessionID, columns, rows) {
    return $Call.ByID(3434639322, sessionID, columns, rows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.TerminalSessionResult.createFrom;
