// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService owns authenticated SSH PTYs, bounded output queues, and Wails events.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close terminates one PTY and emits its final event.
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Close(sessionID) {
    return $Call.ByID(4057890050, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CloseAll terminates every active PTY owned by the desktop process.
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function CloseAll() {
    return $Call.ByID(2902408921).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Input writes ordered UTF-8 terminal input to one PTY.
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Input(sessionID, data) {
    return $Call.ByID(1590750906, sessionID, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Open authenticates an SSH Session, requests xterm-256color PTY, and starts bounded output streaming.
 * @param {string} sshSessionID
 * @param {number} columns
 * @param {number} rows
 * @returns {$CancellablePromise<$models.TerminalSessionResult>}
 */
export function Open(sshSessionID, columns, rows) {
    return $Call.ByID(684388806, sshSessionID, columns, rows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Resize applies a remote window-change request and updates session dimensions.
 * @param {string} sessionID
 * @param {number} columns
 * @param {number} rows
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function Resize(sessionID, columns, rows) {
    return $Call.ByID(3434639322, sessionID, columns, rows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.TerminalSessionResult.createFrom;
