// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DTO is the desktop-safe representation of an application error.
 */
export class DTO {
    /**
     * Creates a new DTO instance.
     * @param {Partial<DTO>} [$$source = {}] - The source object to create the DTO.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["details"] = undefined;
        }
        if (!("retryable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["retryable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DTO}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField2_0($$parsedSource["details"]);
        }
        return new DTO(/** @type {Partial<DTO>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
