// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AlertComparison identifies the bounded numeric comparison used by an alert rule.
 * @readonly
 * @enum {string}
 */
export const AlertComparison = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AlertGreaterThan: "greater_than",
    AlertGreaterThanOrEqual: "greater_than_or_equal",
    AlertLessThan: "less_than",
    AlertLessThanOrEqual: "less_than_or_equal",
};

/**
 * AlertEventState identifies whether a threshold incident is active or recovered.
 * @readonly
 * @enum {string}
 */
export const AlertEventState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AlertEventActive: "active",
    AlertEventRecovered: "recovered",
};

/**
 * FirewallPolicy identifies how MineOps handles the configured Minecraft TCP port.
 * @readonly
 * @enum {string}
 */
export const FirewallPolicy = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    FirewallDisabled: "disabled",
    FirewallPrompt: "prompt",
    FirewallAutomatic: "automatic",
};

/**
 * InstallationState identifies the durable lifecycle of one installation task.
 * @readonly
 * @enum {string}
 */
export const InstallationState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    InstallationWaiting: "waiting",
    InstallationRunning: "running",
    InstallationSucceeded: "succeeded",
    InstallationFailed: "failed",
    InstallationCancelled: "cancelled",
};

/**
 * InstallationStepState identifies one checkpointed installation step lifecycle.
 * @readonly
 * @enum {string}
 */
export const InstallationStepState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    InstallationStepWaiting: "waiting",
    InstallationStepRunning: "running",
    InstallationStepSuccess: "success",
    InstallationStepFailed: "failed",
    InstallationStepSkipped: "skipped",
    InstallationStepCancelled: "cancelled",
};

/**
 * LifecycleState identifies the verified Minecraft server lifecycle.
 * @readonly
 * @enum {string}
 */
export const LifecycleState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    LifecycleCreating: "creating",
    LifecycleInstalling: "installing",
    LifecycleReady: "ready",
    LifecycleStarting: "starting",
    LifecycleRunning: "running",
    LifecycleStopping: "stopping",
    LifecycleStopped: "stopped",
    LifecycleUpdating: "updating",
    LifecycleBackingUp: "backing_up",
    LifecycleDeleted: "deleted",
    LifecycleFailed: "failed",
};

/**
 * MetricAggregation identifies the preferred rollup calculation.
 * @readonly
 * @enum {string}
 */
export const MetricAggregation = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MetricAggregationAverage: "average",
    MetricAggregationSum: "sum",
    MetricAggregationLatest: "latest",
    MetricAggregationMaximum: "maximum",
};

/**
 * MetricGranularity identifies raw, minute, or hour storage/query resolution.
 * @readonly
 * @enum {string}
 */
export const MetricGranularity = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MetricGranularityRaw: "raw",
    MetricGranularityMinute: "minute",
    MetricGranularityHour: "hour",
};

/**
 * MetricType identifies the namespace of a persisted metric sample.
 * @readonly
 * @enum {string}
 */
export const MetricType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MetricHostCPU: "host.cpu",
    MetricHostMemory: "host.memory",
    MetricMinecraftTPS: "minecraft.tps",
    MetricMinecraftMSPT: "minecraft.mspt",
    MetricHostLoad1: "host.load.1m",
    MetricHostMemoryUsed: "host.memory.used",
    MetricHostMemoryTotal: "host.memory.total",
    MetricHostSwapUsed: "host.swap.used",
    MetricHostDiskUsed: "host.disk.used",
    MetricHostDiskTotal: "host.disk.total",
    MetricHostDiskRead: "host.disk.read_bytes_per_second",
    MetricHostDiskWrite: "host.disk.write_bytes_per_second",
    MetricHostNetworkReceive: "host.network.receive_bytes_per_second",
    MetricHostNetworkTransmit: "host.network.transmit_bytes_per_second",
    MetricProcessCPU: "process.cpu",
    MetricProcessRSS: "process.rss",
    MetricProcessThreads: "process.threads",
    MetricProcessFDs: "process.file_descriptors",
    MetricProcessUptime: "process.uptime",
    MetricProcessRunning: "process.running",
    MetricMinecraftPlayers: "minecraft.players",
};

/**
 * MetricUnit identifies the physical or semantic unit of a metric.
 * @readonly
 * @enum {string}
 */
export const MetricUnit = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MetricUnitPercent: "percent",
    MetricUnitBytes: "bytes",
    MetricUnitBytesPerSec: "bytes_per_second",
    MetricUnitCount: "count",
    MetricUnitMilliseconds: "milliseconds",
    MetricUnitTicksPerSec: "ticks_per_second",
    MetricUnitRatio: "ratio",
    MetricUnitSeconds: "seconds",
};

/**
 * MetricValueType identifies how a metric value should be rendered and validated.
 * @readonly
 * @enum {string}
 */
export const MetricValueType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MetricValueGauge: "gauge",
    MetricValueCounter: "counter",
};

/**
 * MinecraftServerType identifies one supported server distribution or proxy family.
 * @readonly
 * @enum {string}
 */
export const MinecraftServerType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ServerVanilla: "vanilla",
    ServerPaper: "paper",
    ServerPurpur: "purpur",
    ServerSpigot: "spigot",
    ServerFabric: "fabric",
    ServerForge: "forge",
    ServerNeoForge: "neoforge",
    ServerQuilt: "quilt",
    ServerFolia: "folia",
    ServerVelocity: "velocity",
    ServerWaterfall: "waterfall",
    ServerBungee: "bungeecord",
};

/**
 * OperationState identifies the durable lifecycle of a long-running operation.
 * @readonly
 * @enum {string}
 */
export const OperationState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    OperationPending: "pending",
    OperationRunning: "running",
    OperationSucceeded: "succeeded",
    OperationFailed: "failed",
    OperationCancelled: "cancelled",
};

/**
 * OperationTargetType identifies the resource class locked by an operation.
 * @readonly
 * @enum {string}
 */
export const OperationTargetType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    OperationTargetServer: "server",
    OperationTargetSSHSession: "ssh_session",
    OperationTargetFile: "file",
    OperationTargetJava: "java_runtime",
    OperationTargetAgent: "agent",
    OperationTargetSettings: "settings",
    OperationTargetSpark: "spark",
};

/**
 * OperationType identifies the user intent executed by a durable operation.
 * @readonly
 * @enum {string}
 */
export const OperationType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    OperationInstall: "install",
    OperationDownload: "download",
    OperationUpload: "upload",
    OperationExtract: "extract",
    OperationStart: "start",
    OperationStop: "stop",
    OperationRestart: "restart",
    OperationBackup: "backup",
    OperationRestore: "restore",
    OperationUpdate: "update",
    OperationDelete: "delete",
    OperationProfile: "profile",
};

/**
 * PlayerActivityAccuracy identifies the confidence of persisted player activity data.
 * @readonly
 * @enum {string}
 */
export const PlayerActivityAccuracy = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlayerAccuracyExact: "exact",
    PlayerAccuracyServerBoundary: "server_boundary",
    PlayerAccuracyEstimated: "estimated",
    PlayerAccuracyReconstructed: "reconstructed",
    PlayerAccuracyIncomplete: "incomplete",
};

/**
 * PlayerIdentityKind identifies the evidence backing a Server-scoped player identity.
 * @readonly
 * @enum {string}
 */
export const PlayerIdentityKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlayerIdentityUUID: "uuid",
    PlayerIdentityNameOnly: "name_only",
};

/**
 * PlayerSessionCloseReason identifies why a player session was settled.
 * @readonly
 * @enum {string}
 */
export const PlayerSessionCloseReason = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlayerCloseLeave: "leave",
    PlayerCloseDuplicateJoin: "duplicate_join",
    PlayerCloseServerStopped: "server_stopped",
    PlayerCloseUnexpectedExit: "unexpected_exit",
    PlayerCloseProcessReplaced: "process_replaced",
    PlayerCloseIdentityMerged: "identity_merged",
};

/**
 * PlayerSessionState identifies whether a player connection is still open or settled.
 * @readonly
 * @enum {string}
 */
export const PlayerSessionState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlayerSessionOpen: "open",
    PlayerSessionClosed: "closed",
    PlayerSessionInterrupted: "interrupted",
};

/**
 * ProxyMode identifies how outbound catalog and artifact HTTP traffic is routed.
 * @readonly
 * @enum {string}
 */
export const ProxyMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ProxyNone: "none",
    ProxySystem: "system",
    ProxyHTTP: "http",
    ProxyHTTPS: "https",
    ProxySOCKS5: "socks5",
};

/**
 * RemoteProcessState identifies probe evidence independently from persisted Server lifecycle state.
 * @readonly
 * @enum {string}
 */
export const RemoteProcessState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RemoteProcessUnknown: "unknown",
    RemoteProcessRunning: "running",
    RemoteProcessExited: "exited",
    RemoteProcessMismatched: "mismatched",
};

/**
 * SparkReportKind identifies one controlled Minecraft spark report workflow.
 * @readonly
 * @enum {string}
 */
export const SparkReportKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SparkReportHealth: "health",
    SparkReportProfiler: "profiler",
};

/**
 * SparkReportState identifies the durable lifecycle of one Minecraft spark report.
 * @readonly
 * @enum {string}
 */
export const SparkReportState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SparkReportPending: "pending",
    SparkReportRunning: "running",
    SparkReportCompleted: "completed",
    SparkReportFailed: "failed",
    SparkReportCancelled: "cancelled",
};

/**
 * SparkStatus identifies Minecraft spark availability independently from Agent state.
 * @readonly
 * @enum {string}
 */
export const SparkStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SparkUnknown: "unknown",
    SparkUnavailable: "unavailable",
    SparkUnsupported: "unsupported",
    SparkAvailable: "available",
    SparkCollecting: "collecting",
    SparkFailed: "failed",
};
