// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AlertComparison 标识告警规则使用的有界数值比较方式。
 * @readonly
 * @enum {string}
 */
export const AlertComparison = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AlertGreaterThan: "greater_than",
    AlertGreaterThanOrEqual: "greater_than_or_equal",
    AlertLessThan: "less_than",
    AlertLessThanOrEqual: "less_than_or_equal",
};

/**
 * AlertEventState 标识一次阈值告警处于活跃还是已恢复。
 * @readonly
 * @enum {string}
 */
export const AlertEventState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AlertEventActive: "active",
    AlertEventRecovered: "recovered",
};

/**
 * FirewallPolicy 标识 MineOps 如何处理已配置的 Minecraft TCP 端口。
 * @readonly
 * @enum {string}
 */
export const FirewallPolicy = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    FirewallDisabled: "disabled",
    FirewallPrompt: "prompt",
    FirewallAutomatic: "automatic",
};

/**
 * InstallationState 标识一个安装任务的持久化生命周期。
 * @readonly
 * @enum {string}
 */
export const InstallationState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    InstallationWaiting: "waiting",
    InstallationRunning: "running",
    InstallationSucceeded: "succeeded",
    InstallationFailed: "failed",
    InstallationCancelled: "cancelled",
};

/**
 * InstallationStepState 标识一个带检查点的安装步骤的生命周期。
 * @readonly
 * @enum {string}
 */
export const InstallationStepState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    InstallationStepWaiting: "waiting",
    InstallationStepRunning: "running",
    InstallationStepSuccess: "success",
    InstallationStepFailed: "failed",
    InstallationStepSkipped: "skipped",
    InstallationStepCancelled: "cancelled",
};

/**
 * LifecycleState 标识经过校验的 Minecraft 服务端生命周期。
 * @readonly
 * @enum {string}
 */
export const LifecycleState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    LifecycleCreating: "creating",
    LifecycleInstalling: "installing",
    LifecycleReady: "ready",
    LifecycleStarting: "starting",
    LifecycleRunning: "running",
    LifecycleStopping: "stopping",
    LifecycleStopped: "stopped",
    LifecycleUpdating: "updating",
    LifecycleBackingUp: "backing_up",
    LifecycleDeleted: "deleted",
    LifecycleFailed: "failed",
};

/**
 * MetricAggregation 标识降采样时首选的聚合算法。
 * @readonly
 * @enum {string}
 */
export const MetricAggregation = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MetricAggregationAverage: "average",
    MetricAggregationSum: "sum",
    MetricAggregationLatest: "latest",
    MetricAggregationMaximum: "maximum",
};

/**
 * MetricGranularity 标识原始、分钟或小时级的存储与查询粒度。
 * @readonly
 * @enum {string}
 */
export const MetricGranularity = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MetricGranularityRaw: "raw",
    MetricGranularityMinute: "minute",
    MetricGranularityHour: "hour",
};

/**
 * MetricType 标识一条持久化指标样本的命名空间。
 * @readonly
 * @enum {string}
 */
export const MetricType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MetricHostCPU: "host.cpu",
    MetricHostMemory: "host.memory",
    MetricMinecraftTPS: "minecraft.tps",
    MetricMinecraftMSPT: "minecraft.mspt",
    MetricHostLoad1: "host.load.1m",
    MetricHostMemoryUsed: "host.memory.used",
    MetricHostMemoryTotal: "host.memory.total",
    MetricHostSwapUsed: "host.swap.used",
    MetricHostDiskUsed: "host.disk.used",
    MetricHostDiskTotal: "host.disk.total",
    MetricHostDiskRead: "host.disk.read_bytes_per_second",
    MetricHostDiskWrite: "host.disk.write_bytes_per_second",
    MetricHostNetworkReceive: "host.network.receive_bytes_per_second",
    MetricHostNetworkTransmit: "host.network.transmit_bytes_per_second",
    MetricProcessCPU: "process.cpu",
    MetricProcessRSS: "process.rss",
    MetricProcessThreads: "process.threads",
    MetricProcessFDs: "process.file_descriptors",
    MetricProcessUptime: "process.uptime",
    MetricProcessRunning: "process.running",
    MetricMinecraftPlayers: "minecraft.players",
};

/**
 * MetricUnit 标识一个指标的物理单位或语义单位。
 * @readonly
 * @enum {string}
 */
export const MetricUnit = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MetricUnitPercent: "percent",
    MetricUnitBytes: "bytes",
    MetricUnitBytesPerSec: "bytes_per_second",
    MetricUnitCount: "count",
    MetricUnitMilliseconds: "milliseconds",
    MetricUnitTicksPerSec: "ticks_per_second",
    MetricUnitRatio: "ratio",
    MetricUnitSeconds: "seconds",
};

/**
 * MetricValueType 标识一个指标值应如何渲染与校验。
 * @readonly
 * @enum {string}
 */
export const MetricValueType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MetricValueGauge: "gauge",
    MetricValueCounter: "counter",
};

/**
 * MinecraftServerType 标识一个受支持的服务端发行版或代理端家族。
 * @readonly
 * @enum {string}
 */
export const MinecraftServerType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ServerVanilla: "vanilla",
    ServerPaper: "paper",
    ServerPurpur: "purpur",
    ServerSpigot: "spigot",
    ServerFabric: "fabric",
    ServerForge: "forge",
    ServerNeoForge: "neoforge",
    ServerQuilt: "quilt",
    ServerFolia: "folia",
    ServerVelocity: "velocity",
    ServerWaterfall: "waterfall",
    ServerBungee: "bungeecord",
};

/**
 * OperationState 标识一个长任务的持久化生命周期。
 * @readonly
 * @enum {string}
 */
export const OperationState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    OperationPending: "pending",
    OperationRunning: "running",
    OperationSucceeded: "succeeded",
    OperationFailed: "failed",
    OperationCancelled: "cancelled",
};

/**
 * OperationTargetType 标识任务所锁定的资源类别。
 * @readonly
 * @enum {string}
 */
export const OperationTargetType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    OperationTargetServer: "server",
    OperationTargetSSHSession: "ssh_session",
    OperationTargetFile: "file",
    OperationTargetJava: "java_runtime",
    OperationTargetAgent: "agent",
    OperationTargetSettings: "settings",
    OperationTargetSpark: "spark",
};

/**
 * OperationType 标识一个持久化任务所执行的用户意图。
 * @readonly
 * @enum {string}
 */
export const OperationType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    OperationInstall: "install",
    OperationDownload: "download",
    OperationUpload: "upload",
    OperationExtract: "extract",
    OperationStart: "start",
    OperationStop: "stop",
    OperationRestart: "restart",
    OperationBackup: "backup",
    OperationRestore: "restore",
    OperationUpdate: "update",
    OperationDelete: "delete",
    OperationProfile: "profile",
};

/**
 * PlayerActivityAccuracy 标识已持久化玩家活动数据的可信程度。
 * @readonly
 * @enum {string}
 */
export const PlayerActivityAccuracy = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlayerAccuracyExact: "exact",
    PlayerAccuracyServerBoundary: "server_boundary",
    PlayerAccuracyEstimated: "estimated",
    PlayerAccuracyReconstructed: "reconstructed",
    PlayerAccuracyIncomplete: "incomplete",
};

/**
 * PlayerIdentityKind 标识支撑某台 Server 内玩家身份的证据来源。
 * @readonly
 * @enum {string}
 */
export const PlayerIdentityKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlayerIdentityUUID: "uuid",
    PlayerIdentityNameOnly: "name_only",
};

/**
 * PlayerSessionCloseReason 标识玩家会话结算的原因。
 * @readonly
 * @enum {string}
 */
export const PlayerSessionCloseReason = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlayerCloseLeave: "leave",
    PlayerCloseDuplicateJoin: "duplicate_join",
    PlayerCloseServerStopped: "server_stopped",
    PlayerCloseUnexpectedExit: "unexpected_exit",
    PlayerCloseProcessReplaced: "process_replaced",
    PlayerCloseIdentityMerged: "identity_merged",
};

/**
 * PlayerSessionState 标识玩家连接仍在进行还是已结算。
 * @readonly
 * @enum {string}
 */
export const PlayerSessionState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlayerSessionOpen: "open",
    PlayerSessionClosed: "closed",
    PlayerSessionInterrupted: "interrupted",
};

/**
 * ProxyMode 标识出站目录与构件 HTTP 流量的路由方式。
 * @readonly
 * @enum {string}
 */
export const ProxyMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ProxyNone: "none",
    ProxySystem: "system",
    ProxyHTTP: "http",
    ProxyHTTPS: "https",
    ProxySOCKS5: "socks5",
};

/**
 * RemoteProcessState 标识探测得到的进程证据,与持久化的 Server 生命周期状态相互独立。
 * @readonly
 * @enum {string}
 */
export const RemoteProcessState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RemoteProcessUnknown: "unknown",
    RemoteProcessRunning: "running",
    RemoteProcessExited: "exited",
    RemoteProcessMismatched: "mismatched",
};

/**
 * SparkReportKind 标识一种受控的 Minecraft spark 报告流程。
 * @readonly
 * @enum {string}
 */
export const SparkReportKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SparkReportHealth: "health",
    SparkReportProfiler: "profiler",
};

/**
 * SparkReportState 标识一份 Minecraft spark 报告的持久化生命周期。
 * @readonly
 * @enum {string}
 */
export const SparkReportState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SparkReportPending: "pending",
    SparkReportRunning: "running",
    SparkReportCompleted: "completed",
    SparkReportFailed: "failed",
    SparkReportCancelled: "cancelled",
};

/**
 * SparkStatus 标识 Minecraft spark 的可用性,与 Agent 状态相互独立。
 * @readonly
 * @enum {string}
 */
export const SparkStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SparkUnknown: "unknown",
    SparkUnavailable: "unavailable",
    SparkUnsupported: "unsupported",
    SparkAvailable: "available",
    SparkCollecting: "collecting",
    SparkFailed: "failed",
};
