// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as services$0 from "../../../../Cail-Gainey/MineOps/internal/desktop/services/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as model$0 from "../../../../Cail-Gainey/MineOps/internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as application$0 from "../pkg/application/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "mineops:alert:event": model$0.AlertEvent;
            "mineops:console:event": services$0.ConsoleEvent;
            "mineops:file-drop": services$0.FileDropEvent;
            "mineops:lifecycle:quit-blocked": services$0.QuitBlockedEvent;
            "mineops:lifecycle:second-instance": application$0.SecondInstanceData;
            "mineops:metric:realtime": model$0.MetricRealtimeEvent;
            "mineops:operation:progress": model$0.Operation;
            "mineops:player:event": model$0.PlayerEvent;
            "mineops:settings:changed": services$0.SettingsChangedEvent;
            "mineops:spike:event-batch": services$0.EventSpikeBatch;
            "mineops:terminal:event": services$0.TerminalEvent;
        }
    }
}
