//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "../../../../Cail-Gainey/MineOps/internal/desktop/services/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../../../Cail-Gainey/MineOps/internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../pkg/application/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "mineops:alert:event": $$createType0,
        "mineops:console:event": $$createType1,
        "mineops:file-drop": $$createType2,
        "mineops:lifecycle:quit-blocked": $$createType3,
        "mineops:lifecycle:second-instance": $$createType4,
        "mineops:metric:realtime": $$createType5,
        "mineops:operation:progress": $$createType6,
        "mineops:player:event": $$createType7,
        "mineops:settings:changed": $$createType8,
        "mineops:spike:event-batch": $$createType9,
        "mineops:terminal:event": $$createType10,
    }));
}

// Private type creation functions
const $$createType0 = model$0.AlertEvent.createFrom;
const $$createType1 = services$0.ConsoleEvent.createFrom;
const $$createType2 = services$0.FileDropEvent.createFrom;
const $$createType3 = services$0.QuitBlockedEvent.createFrom;
const $$createType4 = application$0.SecondInstanceData.createFrom;
const $$createType5 = model$0.MetricRealtimeEvent.createFrom;
const $$createType6 = model$0.Operation.createFrom;
const $$createType7 = model$0.PlayerEvent.createFrom;
const $$createType8 = services$0.SettingsChangedEvent.createFrom;
const $$createType9 = services$0.EventSpikeBatch.createFrom;
const $$createType10 = services$0.TerminalEvent.createFrom;

configure();
