// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../global/enums/models.js";

/**
 * JDKArtifact is the provider-neutral approved Java download description.
 */
export class JDKArtifact {
    /**
     * Creates a new JDKArtifact instance.
     * @param {Partial<JDKArtifact>} [$$source = {}] - The source object to create the JDKArtifact.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("majorVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["majorVersion"] = 0;
        }
        if (!("vendor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vendor"] = "";
        }
        if (!("architecture" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["architecture"] = "";
        }
        if (!("operatingSystem" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operatingSystem"] = "";
        }
        if (!("archiveType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archiveType"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JDKArtifact instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JDKArtifact}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JDKArtifact(/** @type {Partial<JDKArtifact>} */($$parsedSource));
    }
}

/**
 * ServerDistribution describes one dynamically registered server type and its installation capabilities.
 */
export class ServerDistribution {
    /**
     * Creates a new ServerDistribution instance.
     * @param {Partial<ServerDistribution>} [$$source = {}] - The source object to create the ServerDistribution.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {enums$0.MinecraftServerType}
             */
            this["type"] = enums$0.MinecraftServerType.$zero;
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("proxy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["proxy"] = false;
        }
        if (!("catalogReady" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["catalogReady"] = false;
        }
        if (!("installerReady" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installerReady"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerDistribution instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerDistribution}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerDistribution(/** @type {Partial<ServerDistribution>} */($$parsedSource));
    }
}

/**
 * ServerVersion is one provider-neutral version exposed by a server distribution catalog.
 */
export class ServerVersion {
    /**
     * Creates a new ServerVersion instance.
     * @param {Partial<ServerVersion>} [$$source = {}] - The source object to create the ServerVersion.
     */
    constructor($$source = {}) {
        if (!("distribution" in $$source)) {
            /**
             * @member
             * @type {enums$0.MinecraftServerType}
             */
            this["distribution"] = enums$0.MinecraftServerType.$zero;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["build"] = undefined;
        }
        if (!("stable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["stable"] = false;
        }
        if (!("javaMajor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["javaMajor"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerVersion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerVersion}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerVersion(/** @type {Partial<ServerVersion>} */($$parsedSource));
    }
}
