// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../global/enums/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sqlcipher$0 from "../infrastructure/sqlcipher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * BackgroundResource describes the current controlled application background image.
 */
export class BackgroundResource {
    /**
     * Creates a new BackgroundResource instance.
     * @param {Partial<BackgroundResource>} [$$source = {}] - The source object to create the BackgroundResource.
     */
    constructor($$source = {}) {
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dataURL"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["bytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackgroundResource instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackgroundResource}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackgroundResource(/** @type {Partial<BackgroundResource>} */($$parsedSource));
    }
}

/**
 * CollectorStatus 描述一台服务器最近一次 SSH 拉取采集的结果状态。
 */
export class CollectorStatus {
    /**
     * Creates a new CollectorStatus instance.
     * @param {Partial<CollectorStatus>} [$$source = {}] - The source object to create the CollectorStatus.
     */
    constructor($$source = {}) {
        if (!("serverID" in $$source)) {
            /**
             * @member
             * @type {model$0.ID}
             */
            this["serverID"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["collectedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["lastErrorAt"] = undefined;
        }
        if (!("collecting" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["collecting"] = false;
        }
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectorStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectorStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CollectorStatus(/** @type {Partial<CollectorStatus>} */($$parsedSource));
    }
}

/**
 * DesktopUpdateStatus describes the configured channel and complete Desktop self-update lifecycle.
 */
export class DesktopUpdateStatus {
    /**
     * Creates a new DesktopUpdateStatus instance.
     * @param {Partial<DesktopUpdateStatus>} [$$source = {}] - The source object to create the DesktopUpdateStatus.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("channel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["channel"] = "";
        }
        if (!("manifestURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manifestURL"] = "";
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["latestVersion"] = undefined;
        }
        if (!("updateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updateAvailable"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["releaseURL"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["publishedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["notes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["lastCheckedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastErrorCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastErrorMessage"] = undefined;
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("architecture" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["architecture"] = "";
        }
        if (!("installSupported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installSupported"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["installMessage"] = undefined;
        }
        if (!("downloadedBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloadedBytes"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalBytes"] = 0;
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("readyToRestart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["readyToRestart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopUpdateStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DesktopUpdateStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopUpdateStatus(/** @type {Partial<DesktopUpdateStatus>} */($$parsedSource));
    }
}

/**
 * DiagnosticPackage describes one completed redacted diagnostic archive.
 */
export class DiagnosticPackage {
    /**
     * Creates a new DiagnosticPackage instance.
     * @param {Partial<DiagnosticPackage>} [$$source = {}] - The source object to create the DiagnosticPackage.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("generatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("logFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["logFiles"] = 0;
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticPackage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiagnosticPackage}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField4_0($$parsedSource["warnings"]);
        }
        return new DiagnosticPackage(/** @type {Partial<DiagnosticPackage>} */($$parsedSource));
    }
}

/**
 * DownloadCacheStatus describes the current local artifact cache footprint.
 */
export class DownloadCacheStatus {
    /**
     * Creates a new DownloadCacheStatus instance.
     * @param {Partial<DownloadCacheStatus>} [$$source = {}] - The source object to create the DownloadCacheStatus.
     */
    constructor($$source = {}) {
        if (!("directory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["directory"] = "";
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["files"] = 0;
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (!("capacityBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["capacityBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadCacheStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadCacheStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadCacheStatus(/** @type {Partial<DownloadCacheStatus>} */($$parsedSource));
    }
}

/**
 * DownloadSourceStatus contains current reachability, latency, and stable failure details.
 */
export class DownloadSourceStatus {
    /**
     * Creates a new DownloadSourceStatus instance.
     * @param {Partial<DownloadSourceStatus>} [$$source = {}] - The source object to create the DownloadSourceStatus.
     */
    constructor($$source = {}) {
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("latency" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["latency"] = time$0.Duration.$zero;
        }
        if (!("checkedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checkedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorMessage"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadSourceStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadSourceStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadSourceStatus(/** @type {Partial<DownloadSourceStatus>} */($$parsedSource));
    }
}

/**
 * JavaCandidate contains a verified remote Java executable before persistence.
 */
export class JavaCandidate {
    /**
     * Creates a new JavaCandidate instance.
     * @param {Partial<JavaCandidate>} [$$source = {}] - The source object to create the JavaCandidate.
     */
    constructor($$source = {}) {
        if (!("executablePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["executablePath"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {model$0.JavaRuntimeSource}
             */
            this["source"] = model$0.JavaRuntimeSource.$zero;
        }
        if (!("info" in $$source)) {
            /**
             * @member
             * @type {model$0.JavaVersionInfo}
             */
            this["info"] = (new model$0.JavaVersionInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JavaCandidate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JavaCandidate}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("info" in $$parsedSource) {
            $$parsedSource["info"] = $$createField2_0($$parsedSource["info"]);
        }
        return new JavaCandidate(/** @type {Partial<JavaCandidate>} */($$parsedSource));
    }
}

/**
 * LogStatus describes the actual runtime mode, active log file, and bounded directory usage.
 */
export class LogStatus {
    /**
     * Creates a new LogStatus instance.
     * @param {Partial<LogStatus>} [$$source = {}] - The source object to create the LogStatus.
     */
    constructor($$source = {}) {
        if (!("runtimeMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runtimeMode"] = "";
        }
        if (!("directory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["directory"] = "";
        }
        if (!("currentPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentPath"] = "";
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["files"] = 0;
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogStatus(/** @type {Partial<LogStatus>} */($$parsedSource));
    }
}

/**
 * MonitoringIssue distinguishes 采集失败、指标过期、Spark 不可用与 Spark 不兼容。
 */
export class MonitoringIssue {
    /**
     * Creates a new MonitoringIssue instance.
     * @param {Partial<MonitoringIssue>} [$$source = {}] - The source object to create the MonitoringIssue.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitoringIssue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MonitoringIssue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitoringIssue(/** @type {Partial<MonitoringIssue>} */($$parsedSource));
    }
}

/**
 * MonitoringOverview 汇总采集器状态、最新指标、Spark 状态、告警与采集问题。
 */
export class MonitoringOverview {
    /**
     * Creates a new MonitoringOverview instance.
     * @param {Partial<MonitoringOverview>} [$$source = {}] - The source object to create the MonitoringOverview.
     */
    constructor($$source = {}) {
        if (!("serverID" in $$source)) {
            /**
             * @member
             * @type {model$0.ID}
             */
            this["serverID"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CollectorStatus | null | undefined}
             */
            this["collector"] = undefined;
        }
        if (!("latest" in $$source)) {
            /**
             * @member
             * @type {model$0.MetricSample[]}
             */
            this["latest"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {model$0.SparkCapability | null | undefined}
             */
            this["spark"] = undefined;
        }
        if (!("activeAlerts" in $$source)) {
            /**
             * @member
             * @type {model$0.AlertEvent[]}
             */
            this["activeAlerts"] = [];
        }
        if (!("issues" in $$source)) {
            /**
             * @member
             * @type {MonitoringIssue[]}
             */
            this["issues"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["collectedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitoringOverview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MonitoringOverview}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("collector" in $$parsedSource) {
            $$parsedSource["collector"] = $$createField1_0($$parsedSource["collector"]);
        }
        if ("latest" in $$parsedSource) {
            $$parsedSource["latest"] = $$createField2_0($$parsedSource["latest"]);
        }
        if ("spark" in $$parsedSource) {
            $$parsedSource["spark"] = $$createField3_0($$parsedSource["spark"]);
        }
        if ("activeAlerts" in $$parsedSource) {
            $$parsedSource["activeAlerts"] = $$createField4_0($$parsedSource["activeAlerts"]);
        }
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField5_0($$parsedSource["issues"]);
        }
        return new MonitoringOverview(/** @type {Partial<MonitoringOverview>} */($$parsedSource));
    }
}

/**
 * PerformanceOverview combines Spark capability, snapshots, reports, and related host/process metrics.
 */
export class PerformanceOverview {
    /**
     * Creates a new PerformanceOverview instance.
     * @param {Partial<PerformanceOverview>} [$$source = {}] - The source object to create the PerformanceOverview.
     */
    constructor($$source = {}) {
        if (!("serverID" in $$source)) {
            /**
             * @member
             * @type {model$0.ID}
             */
            this["serverID"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {model$0.SparkCapability | null | undefined}
             */
            this["capability"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {model$0.SparkSnapshot | null | undefined}
             */
            this["latestSnapshot"] = undefined;
        }
        if (!("snapshots" in $$source)) {
            /**
             * @member
             * @type {model$0.SparkSnapshot[]}
             */
            this["snapshots"] = [];
        }
        if (!("reports" in $$source)) {
            /**
             * @member
             * @type {model$0.SparkReport[]}
             */
            this["reports"] = [];
        }
        if (!("relatedMetrics" in $$source)) {
            /**
             * @member
             * @type {model$0.MetricSample[]}
             */
            this["relatedMetrics"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PerformanceOverview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PerformanceOverview}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType13;
        const $$createField3_0 = $$createType14;
        const $$createField4_0 = $$createType16;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capability" in $$parsedSource) {
            $$parsedSource["capability"] = $$createField1_0($$parsedSource["capability"]);
        }
        if ("latestSnapshot" in $$parsedSource) {
            $$parsedSource["latestSnapshot"] = $$createField2_0($$parsedSource["latestSnapshot"]);
        }
        if ("snapshots" in $$parsedSource) {
            $$parsedSource["snapshots"] = $$createField3_0($$parsedSource["snapshots"]);
        }
        if ("reports" in $$parsedSource) {
            $$parsedSource["reports"] = $$createField4_0($$parsedSource["reports"]);
        }
        if ("relatedMetrics" in $$parsedSource) {
            $$parsedSource["relatedMetrics"] = $$createField5_0($$parsedSource["relatedMetrics"]);
        }
        return new PerformanceOverview(/** @type {Partial<PerformanceOverview>} */($$parsedSource));
    }
}

/**
 * ProxyCredentialStatus exposes non-secret proxy credential state.
 */
export class ProxyCredentialStatus {
    /**
     * Creates a new ProxyCredentialStatus instance.
     * @param {Partial<ProxyCredentialStatus>} [$$source = {}] - The source object to create the ProxyCredentialStatus.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["credentialID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["username"] = undefined;
        }
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyCredentialStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyCredentialStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyCredentialStatus(/** @type {Partial<ProxyCredentialStatus>} */($$parsedSource));
    }
}

/**
 * RemoteDirectory contains one normalized directory, remote Home, and stable-sorted entries.
 */
export class RemoteDirectory {
    /**
     * Creates a new RemoteDirectory instance.
     * @param {Partial<RemoteDirectory>} [$$source = {}] - The source object to create the RemoteDirectory.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("home" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["home"] = "";
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {model$0.RemoteFile[]}
             */
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteDirectory instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteDirectory}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField2_0($$parsedSource["entries"]);
        }
        return new RemoteDirectory(/** @type {Partial<RemoteDirectory>} */($$parsedSource));
    }
}

/**
 * RemoteServerInspection contains read-only evidence used before importing an existing remote Server.
 */
export class RemoteServerInspection {
    /**
     * Creates a new RemoteServerInspection instance.
     * @param {Partial<RemoteServerInspection>} [$$source = {}] - The source object to create the RemoteServerInspection.
     */
    constructor($$source = {}) {
        if (!("remotePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remotePath"] = "";
        }
        if (!("jars" in $$source)) {
            /**
             * @member
             * @type {RemoteServerJar[]}
             */
            this["jars"] = [];
        }
        if (!("suggestedJar" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["suggestedJar"] = "";
        }
        if (!("suggestedType" in $$source)) {
            /**
             * @member
             * @type {enums$0.MinecraftServerType}
             */
            this["suggestedType"] = enums$0.MinecraftServerType.$zero;
        }
        if (!("suggestedVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["suggestedVersion"] = "";
        }
        if (!("propertiesFound" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["propertiesFound"] = false;
        }
        if (!("eulaFound" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["eulaFound"] = false;
        }
        if (!("eulaAccepted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["eulaAccepted"] = false;
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteServerInspection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteServerInspection}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType20;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("jars" in $$parsedSource) {
            $$parsedSource["jars"] = $$createField1_0($$parsedSource["jars"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField8_0($$parsedSource["warnings"]);
        }
        return new RemoteServerInspection(/** @type {Partial<RemoteServerInspection>} */($$parsedSource));
    }
}

/**
 * RemoteServerJar is one ordinary root-level Jar candidate discovered without changing the remote directory.
 */
export class RemoteServerJar {
    /**
     * Creates a new RemoteServerJar instance.
     * @param {Partial<RemoteServerJar>} [$$source = {}] - The source object to create the RemoteServerJar.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteServerJar instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteServerJar}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteServerJar(/** @type {Partial<RemoteServerJar>} */($$parsedSource));
    }
}

/**
 * ServerBackup is one verified MineOps-managed remote Server backup archive.
 */
export class ServerBackup {
    /**
     * Creates a new ServerBackup instance.
     * @param {Partial<ServerBackup>} [$$source = {}] - The source object to create the ServerBackup.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("modifiedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modifiedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerBackup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerBackup}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerBackup(/** @type {Partial<ServerBackup>} */($$parsedSource));
    }
}

/**
 * ServerInstallationStatus summarizes remote files against durable Server and Installation metadata.
 */
export class ServerInstallationStatus {
    /**
     * Creates a new ServerInstallationStatus instance.
     * @param {Partial<ServerInstallationStatus>} [$$source = {}] - The source object to create the ServerInstallationStatus.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("directoryFound" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["directoryFound"] = false;
        }
        if (!("artifactFound" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["artifactFound"] = false;
        }
        if (!("propertiesFound" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["propertiesFound"] = false;
        }
        if (!("eulaAccepted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["eulaAccepted"] = false;
        }
        if (!("javaRuntimeBound" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["javaRuntimeBound"] = false;
        }
        if (!("artifactPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactPath"] = "";
        }
        if (!("artifactSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["artifactSize"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["actualArtifactHash"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["expectedArtifactHash"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["latestTaskID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {enums$0.InstallationState | undefined}
             */
            this["latestTaskState"] = undefined;
        }
        if (!("issues" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["issues"] = [];
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }
        if (!("inspectedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inspectedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerInstallationStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerInstallationStatus}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField12_0($$parsedSource["issues"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField13_0($$parsedSource["warnings"]);
        }
        return new ServerInstallationStatus(/** @type {Partial<ServerInstallationStatus>} */($$parsedSource));
    }
}

/**
 * ServerPropertiesBackup is one retained pre-save server.properties revision.
 */
export class ServerPropertiesBackup {
    /**
     * Creates a new ServerPropertiesBackup instance.
     * @param {Partial<ServerPropertiesBackup>} [$$source = {}] - The source object to create the ServerPropertiesBackup.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("modifiedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modifiedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerPropertiesBackup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerPropertiesBackup}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerPropertiesBackup(/** @type {Partial<ServerPropertiesBackup>} */($$parsedSource));
    }
}

/**
 * ServerPropertiesSnapshot contains raw text, effective values, and validation information.
 */
export class ServerPropertiesSnapshot {
    /**
     * Creates a new ServerPropertiesSnapshot instance.
     * @param {Partial<ServerPropertiesSnapshot>} [$$source = {}] - The source object to create the ServerPropertiesSnapshot.
     */
    constructor($$source = {}) {
        if (!("document" in $$source)) {
            /**
             * @member
             * @type {model$0.RemoteTextDocument | null}
             */
            this["document"] = null;
        }
        if (!("values" in $$source)) {
            /**
             * @member
             * @type {ServerPropertyValue[]}
             */
            this["values"] = [];
        }
        if (!("serverPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["serverPort"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["validationNotice"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerPropertiesSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerPropertiesSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType22;
        const $$createField1_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("document" in $$parsedSource) {
            $$parsedSource["document"] = $$createField0_0($$parsedSource["document"]);
        }
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField1_0($$parsedSource["values"]);
        }
        return new ServerPropertiesSnapshot(/** @type {Partial<ServerPropertiesSnapshot>} */($$parsedSource));
    }
}

/**
 * ServerPropertyUpdate changes one key while preserving all unrelated physical lines.
 */
export class ServerPropertyUpdate {
    /**
     * Creates a new ServerPropertyUpdate instance.
     * @param {Partial<ServerPropertyUpdate>} [$$source = {}] - The source object to create the ServerPropertyUpdate.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerPropertyUpdate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerPropertyUpdate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerPropertyUpdate(/** @type {Partial<ServerPropertyUpdate>} */($$parsedSource));
    }
}

/**
 * ServerPropertyValue is the effective last value for one server.properties key.
 */
export class ServerPropertyValue {
    /**
     * Creates a new ServerPropertyValue instance.
     * @param {Partial<ServerPropertyValue>} [$$source = {}] - The source object to create the ServerPropertyValue.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerPropertyValue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerPropertyValue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerPropertyValue(/** @type {Partial<ServerPropertyValue>} */($$parsedSource));
    }
}

/**
 * SparkInstallDependency describes one exact dependency installed with a Spark mod.
 */
export class SparkInstallDependency {
    /**
     * Creates a new SparkInstallDependency instance.
     * @param {Partial<SparkInstallDependency>} [$$source = {}] - The source object to create the SparkInstallDependency.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("fallbackURLs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["fallbackURLs"] = [];
        }
        if (!("checksumAlgorithm" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checksumAlgorithm"] = "";
        }
        if (!("checksum" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checksum"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sha256"] = undefined;
        }
        if (!("artifactSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["artifactSize"] = 0;
        }
        if (!("targetPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetPath"] = "";
        }
        if (!("backupPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backupPath"] = "";
        }
        if (!("matchPattern" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["matchPattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SparkInstallDependency instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SparkInstallDependency}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fallbackURLs" in $$parsedSource) {
            $$parsedSource["fallbackURLs"] = $$createField4_0($$parsedSource["fallbackURLs"]);
        }
        return new SparkInstallDependency(/** @type {Partial<SparkInstallDependency>} */($$parsedSource));
    }
}

/**
 * SparkInstallPlan describes an exact approved artifact, source, target, backup, checksum, and restart impact.
 */
export class SparkInstallPlan {
    /**
     * Creates a new SparkInstallPlan instance.
     * @param {Partial<SparkInstallPlan>} [$$source = {}] - The source object to create the SparkInstallPlan.
     */
    constructor($$source = {}) {
        if (!("serverID" in $$source)) {
            /**
             * @member
             * @type {model$0.ID}
             */
            this["serverID"] = "";
        }
        if (!("serverName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverName"] = "";
        }
        if (!("serverType" in $$source)) {
            /**
             * @member
             * @type {enums$0.MinecraftServerType}
             */
            this["serverType"] = enums$0.MinecraftServerType.$zero;
        }
        if (!("currentStatus" in $$source)) {
            /**
             * @member
             * @type {enums$0.SparkStatus}
             */
            this["currentStatus"] = enums$0.SparkStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["currentVersion"] = undefined;
        }
        if (!("targetVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetVersion"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["releaseID"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("build" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["build"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("checksumAlgorithm" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checksumAlgorithm"] = "";
        }
        if (!("checksum" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checksum"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sha256"] = undefined;
        }
        if (!("artifactSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["artifactSize"] = 0;
        }
        if (!("targetPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetPath"] = "";
        }
        if (!("backupPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backupPath"] = "";
        }
        if (!("dependencies" in $$source)) {
            /**
             * @member
             * @type {SparkInstallDependency[]}
             */
            this["dependencies"] = [];
        }
        if (!("restartRequired" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["restartRequired"] = false;
        }
        if (!("impact" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["impact"] = "";
        }
        if (!("generatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("planDigest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["planDigest"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SparkInstallPlan instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SparkInstallPlan}
     */
    static createFrom($$source = {}) {
        const $$createField18_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dependencies" in $$parsedSource) {
            $$parsedSource["dependencies"] = $$createField18_0($$parsedSource["dependencies"]);
        }
        return new SparkInstallPlan(/** @type {Partial<SparkInstallPlan>} */($$parsedSource));
    }
}

/**
 * SparkInstallResult contains the installed capability and exact plan used for the mutation.
 */
export class SparkInstallResult {
    /**
     * Creates a new SparkInstallResult instance.
     * @param {Partial<SparkInstallResult>} [$$source = {}] - The source object to create the SparkInstallResult.
     */
    constructor($$source = {}) {
        if (!("capability" in $$source)) {
            /**
             * @member
             * @type {model$0.SparkCapability}
             */
            this["capability"] = (new model$0.SparkCapability());
        }
        if (!("plan" in $$source)) {
            /**
             * @member
             * @type {SparkInstallPlan}
             */
            this["plan"] = (new SparkInstallPlan());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SparkInstallResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SparkInstallResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capability" in $$parsedSource) {
            $$parsedSource["capability"] = $$createField0_0($$parsedSource["capability"]);
        }
        if ("plan" in $$parsedSource) {
            $$parsedSource["plan"] = $$createField1_0($$parsedSource["plan"]);
        }
        return new SparkInstallResult(/** @type {Partial<SparkInstallResult>} */($$parsedSource));
    }
}

/**
 * StorageStatus describes the active encrypted database and staged offline maintenance.
 */
export class StorageStatus {
    /**
     * Creates a new StorageStatus instance.
     * @param {Partial<StorageStatus>} [$$source = {}] - The source object to create the StorageStatus.
     */
    constructor($$source = {}) {
        if (!("databasePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["databasePath"] = "";
        }
        if (!("dataDirectory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataDirectory"] = "";
        }
        if (!("databaseBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["databaseBytes"] = 0;
        }
        if (!("encrypted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["encrypted"] = false;
        }
        if (!("automaticKeyStore" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["automaticKeyStore"] = false;
        }
        if (!("automaticOpen" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["automaticOpen"] = false;
        }
        if (!("databaseID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["databaseID"] = "";
        }
        if (!("keyVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["keyVersion"] = 0;
        }
        if (!("pendingMaintenance" in $$source)) {
            /**
             * @member
             * @type {sqlcipher$0.PendingMaintenance}
             */
            this["pendingMaintenance"] = (new sqlcipher$0.PendingMaintenance());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StorageStatus}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pendingMaintenance" in $$parsedSource) {
            $$parsedSource["pendingMaintenance"] = $$createField8_0($$parsedSource["pendingMaintenance"]);
        }
        return new StorageStatus(/** @type {Partial<StorageStatus>} */($$parsedSource));
    }
}

/**
 * UnsavedItem identifies one frontend editor or form currently holding uncommitted work.
 */
export class UnsavedItem {
    /**
     * Creates a new UnsavedItem instance.
     * @param {Partial<UnsavedItem>} [$$source = {}] - The source object to create the UnsavedItem.
     */
    constructor($$source = {}) {
        if (!("owner" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["owner"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnsavedItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UnsavedItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UnsavedItem(/** @type {Partial<UnsavedItem>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = model$0.JavaVersionInfo.createFrom;
const $$createType2 = CollectorStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.MetricSample.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.SparkCapability.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.AlertEvent.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = MonitoringIssue.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = model$0.SparkSnapshot.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Array($$createType12);
const $$createType15 = model$0.SparkReport.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = model$0.RemoteFile.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = RemoteServerJar.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = model$0.RemoteTextDocument.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = ServerPropertyValue.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = SparkInstallDependency.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = SparkInstallPlan.createFrom;
const $$createType28 = sqlcipher$0.PendingMaintenance.createFrom;
