// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BackupInfo 描述一份已完成的便携加密 SQLite 备份。
 */
export class BackupInfo {
    /**
     * Creates a new BackupInfo instance.
     * @param {Partial<BackupInfo>} [$$source = {}] - The source object to create the BackupInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("databaseID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["databaseID"] = "";
        }
        if (!("schemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schemaVersion"] = 0;
        }
        if (!("keyVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["keyVersion"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupInfo(/** @type {Partial<BackupInfo>} */($$parsedSource));
    }
}

/**
 * PendingMaintenance 描述排队到下次启动执行的离线数据库任务。
 */
export class PendingMaintenance {
    /**
     * Creates a new PendingMaintenance instance.
     * @param {Partial<PendingMaintenance>} [$$source = {}] - The source object to create the PendingMaintenance.
     */
    constructor($$source = {}) {
        if (!("restorePending" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["restorePending"] = false;
        }
        if (!("keyRotationPending" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keyRotationPending"] = false;
        }
        if (!("vacuumPending" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["vacuumPending"] = false;
        }
        if (!("resetPending" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["resetPending"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {BackupInfo | null | undefined}
             */
            this["restoreBackup"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PendingMaintenance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PendingMaintenance}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("restoreBackup" in $$parsedSource) {
            $$parsedSource["restoreBackup"] = $$createField4_0($$parsedSource["restoreBackup"]);
        }
        return new PendingMaintenance(/** @type {Partial<PendingMaintenance>} */($$parsedSource));
    }
}

/**
 * SpikeResult 承载可观测的 SQLCipher、GORM、事务与磁盘加密证据。
 */
export class SpikeResult {
    /**
     * Creates a new SpikeResult instance.
     * @param {Partial<SpikeResult>} [$$source = {}] - The source object to create the SpikeResult.
     */
    constructor($$source = {}) {
        if (!("cipherVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cipherVersion"] = "";
        }
        if (!("journalMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["journalMode"] = "";
        }
        if (!("busyTimeoutMillis" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["busyTimeoutMillis"] = 0;
        }
        if (!("foreignKeysEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["foreignKeysEnabled"] = false;
        }
        if (!("migrationVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["migrationVersion"] = 0;
        }
        if (!("transactionCommitted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["transactionCommitted"] = false;
        }
        if (!("transactionRolledBack" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["transactionRolledBack"] = false;
        }
        if (!("integrityCheckOK" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["integrityCheckOK"] = false;
        }
        if (!("cipherIntegrityOK" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cipherIntegrityOK"] = false;
        }
        if (!("foreignKeyCheckOK" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["foreignKeyCheckOK"] = false;
        }
        if (!("encryptedHeader" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["encryptedHeader"] = false;
        }
        if (!("plaintextAbsent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["plaintextAbsent"] = false;
        }
        if (!("wrongKeyRejected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["wrongKeyRejected"] = false;
        }
        if (!("correctKeyReopened" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["correctKeyReopened"] = false;
        }
        if (!("databaseBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["databaseBytes"] = 0;
        }
        if (!("databaseIdentity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["databaseIdentity"] = "";
        }
        if (!("automaticKeyRead" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["automaticKeyRead"] = false;
        }
        if (!("keyFileModeSecure" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keyFileModeSecure"] = false;
        }
        if (!("keyRotationSucceeded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keyRotationSucceeded"] = false;
        }
        if (!("oldKeyRejected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["oldKeyRejected"] = false;
        }
        if (!("backupCreated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["backupCreated"] = false;
        }
        if (!("backupRestored" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["backupRestored"] = false;
        }
        if (!("tamperDetected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tamperDetected"] = false;
        }
        if (!("backupBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["backupBytes"] = 0;
        }
        if (!("keyVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["keyVersion"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpikeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SpikeResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpikeResult(/** @type {Partial<SpikeResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = BackupInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
